### ISSUE TITLE
Theme par défaut: pb affichage tags

### ISSUE THREAD

**Issue by pluxml** [pluxml/PluXml#101]
Problème d'affichage des tags dans la sidebar. Le retour en fin de ligne ne se fait pas: les tags sortent de la sibar à droite

dans le fichier: themes/defaut/css/theme.css

remplacer
```
.aside ul.tag-list li {
   display: inline;
   margin-right: 1rem;
}
```
par
```
.aside ul.tag-list li {
   display: inline-block;
   margin-right: 1rem;
}
```

**Comment by RenaudR** [comment]
@pluxml Fonctionne parfaitement avec cette solution.

**Comment by jos-pluxml** [comment]
J'ai corrigé ce bug en modifiant le display comme tu me l'as indiqué.
