### ISSUE TITLE
Impossible de voir les plugins sur l'admin

### ISSUE THREAD

**Issue by AutentiiK** [pluxml/PluXml#111]
Bonjour,
Les plugins que je tente d'installer n'apparaissent pas sur le backoffice. Je suis bien dans la catégorie plugins inactifs et pourtant impossible de visualer le plugin ckeditor ou encore google analytics.
J'ai essayé la même manip chez deux hébergeurs différents, j'ai re-téléchargé les archives et ai pris soin de reverifier le chemin de mes dossiers sur le FTP, rien n'y fait ...
Je suis ouvert à toute suggestion,
Merci pour votre temps.

**Comment by Deevad** [comment]
@AutentiiK  Bonjour, télécharges-tu les archives depuis Github ? 
Si c'est le cas, à mon souvenir les dossiers finissent souvent par "-master" ( eg. plxeditor-master ) de cette façon , ou d'une autre. Hors, le nom du dossier du plugin doit être égal au nom du script *.php contenu à l'intérieur. ( eg. plugin dossier plxMyAkismet contient plxMyAkismet.php ). Ca m'a aussi bloqué une fois.

Une autre piste ; peut-être des permissions insuffisante sur les dossier cible.

**Comment by Pluxopolis** [comment]
Bonjour
http://pluxopolis.net/myplugins#problem

**Comment by jerrywham** [comment]
C'est le repo de pluxml qui est à cette adresse. Vérifie, via FTP, le dossier contenant TES copies des plugins sur ton serveur. S'ils contiennent "-master", renomme les en supprimant "-master" comme te l'as dit Deevad.

**Comment by AutentiiK** [comment]
Après avoir renommé les dossiers du même nom que les fichiers .php les plugins apparaissent bien dans le backoffice.
Merci pour votre aide !
