### ISSUE TITLE
Bug : encodage des caractères sur le titre d'un article

### ISSUE THREAD

**Issue by Draky50110** [pluxml/PluXml#112]
Salut

J'ai créé un article dont le titre est en gros "L'Œil du mal" avec donc un bel oe majuscule.
Pas de souci pour rédiger l'article mais... dans la liste des articles de l'administration, il apparaît comme ça :  L'?il du mal
Je pense qu'il s'agit d'un souci d'encodage ?

**Comment by Pluxopolis** [comment]
Bonjour

Vérifie que l'encodage du fichier core/admin/index.php est bien en UTF-8 sans BOM
Pas de problème d'affichage chez moi avec ton exemple

**Comment by Draky50110** [comment]
Je confirme qu'il est en UTF8 sans BOM :/

Du coup je viens de créer un article avec juste les mots Oeil et oeil etc. et ça passe.
Mais si j'efface le titre de l'article de base et que je le remets, ça foire.
@Pluxopolis peux-tu tester carrément de titre : 
Eagle Eye (L'Œil du mal) : entre surveillance de masse actuelle et Terminator

Je me demande si c'est pas l'apostrophe avant qui fait foirer, en fait j'ai copié-coller le Oe majuscule car sous Windows je n'ai pas mis le clavier oss-fr ;)

**Comment by pluxml** [comment]
en copiant le titre complet, j'ai le bug effectivement

**Comment by Draky50110** [comment]
Du coup je ne vois pas de quoi ça vient...

**Comment by pluxml** [comment]
L'affichage du titre passe par la méthode plxUtils::strCut() pour limiter le texte à un certain nombre de caractères pour ne pas être trop long et décaler les colonnes du tableaux.
C'est cette fonction qui pose problème car elle coupe le texte sans tenir compte de l'encodage des caractères

**Comment by jerrywham** [comment]
Il vaut mieux utiliser mb_substr que substr dans cette fonction. C'est fait pour les caractères multi-octets.

**Comment by pluxml** [comment]
jusqu'à présent on a privilégié substr plutôt que mb_substr car ça oblige d'avoir l'extension mb_string d'installée sur le server

**Comment by jerrywham** [comment]
Oui, c'est sûr.
Pour le bug, je ne parviens pas à le reproduire (pluxml fraîchement téléchargé sur un wampserver)...

**Comment by pluxml** [comment]
@jerrywham : en copiant ce titre ça bug

Eagle Eye (L'Œil du mal) : entre surveillance de masse actuelle et Terminator

**Comment by Draky50110** [comment]
Il existe des hébergeur sans mbstring ?
Parce qu'elle ne pose pas de problème de sécurité cette extension, non ?
Et après... à voir s'il ne faut pas le demander en requis parce que j'ai d'autres scripts qui l'utilisent.
Si des russes ou des chinois ou des arabophones veulent utiliser PluXml ça va merder, non ?

**Comment by jerrywham** [comment]
```` php
plxUtils::strCheck(utf8_decode(plxUtils::strCut(utf8_encode($plxAdmin->plxRecord_arts->f('title')),60)))
````
Ça résout le problème.

**Comment by jerrywham** [comment]
Les fonctions utf8_encode et utf8_decode sont inversées dans la fonction strCut. Il vaut mieux écrire ça, ligne 548 : 
```php
return strlen($str) > $length ? utf8_decode(substr(utf8_encode($str), 0, $length)).$add_text : $str;
```

**Comment by pluxml** [comment]
Dans ce cas là ça serait pas mieux de remonter la fonction utf8_decode dans les méthodes strCheck et strCut (classe plxUtils).
a voir s'il n'y a pas d'effets de bords..

```
public static function strCheck($str) {
   $str = utf8_decode($str);
   ...
}

public static function strCut($str='', $length=25, $type='', $add_text='...') {
   $str = utf8_decode($str);
   ...
}
```

**Comment by jerrywham** [comment]
Euh, non ! Pourquoi tu veux faire ça (surtout dans strCheck) ????

**Comment by pluxml** [comment]
si la résolution du problème consiste à inverser utf8_encode et utf8_decode alors oui c'est mieux

**Comment by jerrywham** [comment]
Ok, on a croisé nos réponses...

**Comment by Draky50110** [comment]
Heu @jerrywham et @pluxml j'ai un souci avec la correction je pense.
Dans l'admin, le titre "Video to Video Converter : le convertisseur de formats vidéo gratuit ultime sous Windows" est vide !
Dans la liste des articles je parle.
Du coup, pour léditer, je ne peux pas cliquer dessus... mais quand j'entre le lien (avec l'ID) direct, je peux l'éditer...

**Comment by pluxml** [comment]
@Draky50110 Je n'arrive pas à reproduire le problème avec le titre de l'article: "Video to Video Converter : le convertisseur de formats vidéo gratuit ultime sous Windows"

**Comment by Draky50110** [comment]
@pluxml je vais passer le blog en mode "github" après une sauvegarde...

On verra si ça continue de foirer...

**Comment by Draky50110** [comment]
Bon, j'ai plus de soucis mais j'en ai d'autres... donc nouveau sujet ;)
