### ISSUE TITLE
Bug : espacement de texte sur la pagination des articles dans l'admin

### ISSUE THREAD

**Issue by Draky50110** [pluxml/PluXml#113]
Salut

Un petit bug visuel survient dans le listing des articles.
J'ai 5 pages d'articles, donc la liste commence par " page 1 sur 5 suivante»" mais dès que je passe sur une autre page, j'ai "précédentePage 2 sur 5 suivante»" c'est-à-dire que le mot "précédente" est collé au mot "Page" ;)
C'est mineur mais voilà :)

**Comment by Pluxopolis** [comment]
Salut

C'est pris en compte et déjà corrigé dans la version github
Merci

**Comment by Draky50110** [comment]
:+1:
