### ISSUE TITLE
Bug : tableaux dans l'admin

### ISSUE THREAD

**Issue by Draky50110** [pluxml/PluXml#116]
Salut

J'ai la dernière version GitHub.
La liste des articles a maintenant un ascenseur horizontal alors que la colonne des catégories est super grande et comme mes catégories ont un nom "court".
Je pense que la taille de la colonne est grande car le menu déroulant de choix de filtre est grand.

Du coup ça fait "vide" et l'ascenseur horizontal est... bref.

Par contre, je précise que l'ascenseur est là car je suis en résolution 1280x800 peut-être.

**Comment by pluxml** [comment]
Bonjour

Quelle est ton navigateur et sur quel OS es-tu ?
Merci

**Comment by Draky50110** [comment]
Le test a été réalisé sous Ubuntu et Firefox.

Par contre, sous Win7 + FF, avec une résolution plus grande (1920x1080), pas d'ascenseur horizontal mais une césure plus courte...
Je mets une capture écran : https://lut.im/FnoQzPlb/Gb1wePyJ

**Comment by pluxml** [comment]
La césure vient de l'utilisation à l'affichage de la fonction plxUtils::strCut
Je l'ai supprimée dans un des derniers commit

**Comment by pluxml** [comment]
ajout d'un wrap (class css .wrap)
