### ISSUE TITLE
Bug : colonne et ligne des tableaux peu lisibles

### ISSUE THREAD

**Issue by Draky50110** [pluxml/PluXml#117]
Salut

Depuis la version 5.4 (je suis en GitHub), les tableaux (liste des articles, liste des commentaires) sont sans "cadres" (pas de lignes horizontales et verticales pour délimiter).
Possible de ravoir ces lignes ?

**Comment by pluxml** [comment]
Salut 
Je t'invite à utiliser ce forum pour remonter ce genre de chose (ou autres) plutot que dans la partie issue de github. Ce n'est pas un bug, c'est un choix volontaire sur la mise en page des tableaux

http://forum.pluxml.org/viewforum.php?id=25

**Comment by Draky50110** [comment]
Ok :)
