### ISSUE TITLE
Bug : fonction de renvoi de numéro de commentaire

### ISSUE THREAD

**Issue by Draky50110** [pluxml/PluXml#123]
Salut

La fonction $plxShow->comId(); renvoi, pour les 10 premiers commentaires d'un billet, l'ID 1 puis reprends le compte normalement pour 11, 12, etc.
Exemple : c0057-1 puis c0057-1 au lieu de c0057-2 puis c0057-1 au lieu de c0057-3 etc. et ensuite il y a bien c0057-11 puis c0057-12, etc.

**Comment by pluxml** [comment]
Bonjour Draky
Je ne constate pas le problème. Je n'arrive pas à le reproduire.
Peux-tu stp me décrire le processus pour avoir le bug ?
Merci

**Comment by Draky50110** [comment]
En fait, j'avais un souci avec le plugin Gravatar de Jormun sur tes dernières versions de PluXml (récup. ici).
Il m'affichait n'importe quoi en avatar/Gravatar.

Je lui ai demandé par e-mail, et il m'a répondu ça en regardant le code sorti par mon blog.

Je te copie-colle : 

>Dans le code que mon plugin génère, ya normalement la liste des commentaires et les gravatars associés :
>"c0057-1":"http://www.gravatar.com/avatar/fd6037e0417fb0a6fe948de125e6d421.jpg?s=48&d=wavatar",
>"c0057-1":"http://www.gravatar.com/avatar/29b264aac72d096faf7aa096a37628f5.jpg?s=48&d=wavatar",
>"c0057-1":"http://www.gravatar.com/avatar/893af5c9b7c1cb526e713ec93a3ac5c3.jpg?s=48&d=wavatar",
>"c0057-1":"http://www.gravatar.com/avatar/29b264aac72d096faf7aa096a37628f5.jpg?s=48&d=wavatar",
>"c0057-1":"http://www.gravatar.com/avatar/11e38f76f9bc37ae64e06cfd0e346d1b.jpg?s=48&d=wavatar",
>"c0057-1":"http://www.gravatar.com/avatar/29b264aac72d096faf7aa096a37628f5.jpg?s=48&d=wavatar",
>"c0057-1":"http://www.gravatar.com/avatar/97685ec60cbe5b330f431f9c4b8da633.jpg?s=48&d=wavatar",
>"c0057-1":"http://www.gravatar.com/avatar/29b264aac72d096faf7aa096a37628f5.jpg?s=48&d=wavatar",
>"c0057-11":"http://www.gravatar.com/avatar/bd13cbb39572efabc0d26fcff32fdf6a.jpg?s=48&d=wavatar",
>"c0057-12":"http://www.gravatar.com/avatar/29b264aac72d096faf7aa096a37628f5.jpg?s=48&d=wavatar"
> 
>On voit que pour les 10 premiers au lieu de mettre 1 a 10 il met toujorus 1. a partir de 11 ca remarche.
> 
>Or ces fameux 1 a 10, c'est pas moi, j'appelle une fonction pluxml
>$plxShow->comId();
> 
>Et c'est donc lui qui renvoit 1 pour les com 1 a 10. Voilou...

Donc je remonte ça ici, car si c'est un bug...

Je sais que Jormun est parti avec pertes et fracas hein ;) mais bon.

Voilà !

**Comment by pluxml** [comment]
Ok je pense savoir donc que quoi ça vient. Confirme moi si tu es dans ce cas de figure.

Tu es sur un PluXml avec des anciens commentaires de la 5.4 (donc avoir l'ancien système de numérotation des commentaires) et des nouveaux commentaires créés après avoir fait la mise à jour de PluXml avec la version en cours de dev.

Je n'ai pas encore écrit le script de migration qui doit réindexer tous les commentaires des articles, car avec PluXml 5.4 tous les fichiers xml des commentaires sont du type xxxx.xxxxxxxxxx-1.xml alors qu'avec le nouveau système on aura  xxxx.xxxxxxxxxx-1.xml  xxxx.xxxxxxxxxx-2.xml, etc...
Donc pour les anciens coms tu as c0057-1  et dès que tu as les nouveaux commentaires fait après la mise à jour avec le nouveau système ça renvoie correctement c0057-11 puis c0057-12, etc...

**Comment by Draky50110** [comment]
Tu as trouvé !
Tu es génial :D 
Donc voilà.
Plus qu'à attendre le script.
En fait j'ai mis à jour pour la troncature des titres dans l'admin et je n'avais pas réussi à revenir en arrière après sur la 5.4...
