### ISSUE TITLE
Pagination dans le back-office

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#128]
dans core/admin/index.php, le tag p , après le formulaire, contenant l'appel du hook AdminIndexPagination n'a pas d'attribut id. Cela complique l'énoncé des règles CSS pour la mise en forme de la pagination.
Exemple de modif demandée :
form method="post" id="form_articles"
.....
/form
p id="pagination"
php eval($plxAdmin->plxPlugins->callHook('AdminIndexPagination'));
......
/p
idem pour core/admin/comments.php

Autre point.
Dans la gestion des pages statiques, il n'y a pas de pagination.
Peut-on avoir un hook AdminStaticPagination :
<form action="statiques.php" method="post" id="form_statics">
....
/form
p id="pagination"
php eval($plxAdmin->plxPlugins->callHook('AdminStaticPagination'));
.....
/p

Désolé, impossible de mettre correctement les tags html corrects sur le submit

**Comment by pluxml** [comment]
Bonjour

Au lieu d'un hook AdminStaticPagination  tu peux utiliser AdminStaticsFoot à la place

Pour l'id pagination c'est ok
