### ISSUE TITLE
formulaire commentaire: type du champ

### ISSUE THREAD

**Issue by nIQnutn** [pluxml/PluXml#129]
dans commentaires.php, le formulaire on pourrait spécifier le type du champ.
pour l'email et le site on aurait:

      type="email"
      type="url"

pour le moment on a 

			<div class="grid">
				<div class="col sml-12 lrg-6">
					<label for="id_mail"><?php $plxShow->lang('EMAIL') ?> :</label>
					<input id="id_mail" name="mail" type="text" size="20" value="<?php $plxShow->comGet('mail',''); ?>" />
				</div>
				<div class="col sml-12 lrg-6">
					<label for="id_site"><?php $plxShow->lang('WEBSITE') ?> :</label>
					<input id="id_site" name="site" type="text" size="20" value="<?php $plxShow->comGet('site',''); ?>" />
				</div>

**Comment by pluxml** [comment]
Bonjour
Merci pour la proposition, mais non car ces 2 types html5 ne sont pas reconnus par tous les navigateurs (safari en l'occurence). Donc par souci de compatibilité, l'idée n'est pas retenue.

**Comment by pluxml** [comment]
Plus d'infos: http://www.w3schools.com/html/html_form_input_types.asp

**Comment by nIQnutn** [comment]
pour info, j'ai testé sur safari 5.0, le formulaire peut bien être validé.
par contre si le champ est mal rempli, aucun message n’apparaît.
