### ISSUE TITLE
Espaces insécables dans le titre du site ou ailleurs

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#141]
Bonjour,
J'ai un titre assez long sur un site : *Les Fables de laFontaine et autres trucs* .
Sur un PC, l'écran est assez large pour l'afficher sur une ligne.
Par contre, l'usage des tablettes se développe de plus en plus et l'écran n'est plus aussi large.
En conséquence, l'affichage doit se fait sur 2 lignes, sans prévoir où se fera le retour à la ligne, par exemple après  *autres*, ce qui en français  n'est pas correct. D'où l'idée d'utiliser les espaces insécables avec l'entité html **&amp;nbsp;**.
Hélas pour afficher le titre du site, on utilise la fonction php htmlspecialchars() qui convertit par défaut le caractère &amp;
Pour corriger cela, dans la fonction **PlxUtils::strCheck()**, il faut utiliser **htmlspecialchars** comme suit :  
```php
    return htmlspecialchars($str,ENT_QUOTES,PLX_CHARSET, false);
```
Voir la doc à propos de **$double_encode** ici http://php.net/manual/fr/function.htmlspecialchars.php

Peut-on corriger cela dans la version en développement ?

**Comment by pluxml** [comment]
Bonjour
J'aurais dit oui tout de suite si ça n'imposait pas d'avoir PHP 5.2.3 ($double_encode ajouté à partir de php 5.2.3), car du coup ça rajoute une contrainte sur la compatibilité de PluXml avec les versions de PHP dispos sur les hébergeurs. Actuellement PluXml requiert php 5+ et avec c'est modif php 5.2.3+ 
ça demande reflexion si on fait le pas...

**Comment by bazooka07** [comment]
Je pense qu'il faut se limiter aux versions de PHP téléchargeables sur le site de php.net. J'avais dire donc à partir de la version 5.4, mais même celle ci n'est plus disponible avec la version 7.0. Quitte à faire un test à l'installation ou à lla mise à jour de Pluxml.

**Comment by pluxml** [comment]
Le souci est que les hébergeurs ont toujours plusieurs longueurs de retard avant de mettre à jour leur version de php. Donc se référer aux versions dispos sur php.net n'est pas un bon indicateur pour moi.
En revanche on peut peut-etre adapter le code de la fonction strCheck pour qu'il tienne compte de la version de php et appliquer le paramètre $double_encode ou pas. Ce qui me gène dans ce cas là c'est qu'on va rajouter un test dans une fonction qui est énormément utilisé avec peut-etre un impact au niveau performances. Il faut arriver à faire ça le + habilement possible.

**Comment by bazooka07** [comment]
La plupart des hébergeurs payants proposent la version 5.6 par défaut. Chez OVH, qui le 1er hébergeur européen et le 3ème mondial, on peut encore utiliser la 5.4 si on le souhaite.
AMHA, les hébergeurs qui sont avec une plus vieille version de PHP sont ceux qui proposent un hébergeur gratuit, et je pense que cela concerne surtout les FAI.
Pour ta dernière remarque on peut faire le test et appeler htmlspecialchars dans PlxShow:ArtTitle.
Mais c'est une solution un peu batarde, d'autres fonctions de Pluxml doivent être concernées.

**Comment by pluxml** [comment]
Tu as raison. php 5.4 doit certainement etre la plus ancienne version utilisée. Donc on peut surement se permettre de faire la modif que tu proposes. En revanche ça demandera à rajouter un test sur les prérequis à l'installation pour utiliser PluXml (+ maj de la doc)

**Comment by pluxml** [comment]
Je viens de faire un test avec un titre de site très long. En redimensionnant la fenêtre de mon navigateur les retours à la ligne se font très bien et le titre et très bien affiché.
Peux-tu me donner plus de détail sur ton problème. 
Ça ne serait pas lié à ton navigateur, plutôt qu'à la façon dont le titre du site est affiché par PluXml ?
Sur quelle plateforme et quel navigateur constates-tu ton problème de retour à la ligne avec le titre du site ?

**Comment by bazooka07** [comment]
Le problème est qu'il faut que les retours à la ligne se fassent au bon endroit, de façon logique par rapport au français.
Si je prends la phrase "**Les Fables de la Fontaine et autres trucs**", quand l'écran est assez large la phrase s'affiche sur une ligne.
Si maintenant, on réduit progressivement l'écran, le premier retour à la ligne se fera entre les mots **autres** et **trucs**. En français, ce n'est pas logique car les mots autres et trucs sont liés. D'où le besoin de les séparer par un espace insécable pour qu'ils restent ensemble au premier saut de ligne, en saisissant l'entité numérique &amp;nbso; directement dans Pluxml.
Hélas la fonction htmlspecial transforme le caractère &amp; même s'il appartient à une entité html. Du coup, on voit afficher la chaine **&amp;nbsp;** entre les 2 mots au lieu d'un espace.

**Comment by pluxml** [comment]
Ok je comprends mieux. Dans ce cas ma réponse et non pour implémenter cette option car cela va casser le responsive au niveau affichage. 
De plus je ne vois aucun besoin, ni justification par rapport au français pour ne pas séparer "autres" et "trucs" si je reprends ton exemple si on redimensionne la fenêtre.
