### ISSUE TITLE
PlxShow::tagList

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#142]
J'avais fait un pull request pour corriger 2 bugs dans **PlxShow:TagList()** : 
- Lorsqu'on utilise le paramètre **&dollar;max**, le résultat retourné est faux car on prend d'abord &dollar; tags et on trie ensuite, alors qu'il faut trier d'abord et prendre &dollar;  tags
- Il n'y a pas de mise à l'échelle pour la class **tag-size-xx**. Si tous les tags sont peu utilisés, comme au démarrage du site, tout est affiché en petit. Si tous les tags sont beaucoup utilisés, tout est affiché en grand.

Hélas, cela ne figure plus dans la branche master actuellement.
C'est un oubli ou quelqu'un a trouvé un bug ?

**Comment by pluxml** [comment]
Les modifs de taglist n'ont pas encore été testées
