### ISSUE TITLE
Améliorer la structure des URL

### ISSUE THREAD

**Issue by hocktor** [pluxml/PluXml#145]
Je teste actuellement PluXML pour les besoins d'un projet.

Globalement, le CMS fait ce qu'on lui demande de faire. Cependant, j'ai remarqué une chose qui n'est pas bonne au niveau du SEO.

Dès que l'on ajoute une catégorie, l'url de cette catégorie sera sous cette forme :
- première catégorie : categorie1/nom-cat-A
- seconde catégorie : categorie2/nom-cat-B
- ...

il vaudrait mieux avoir la structure suivante :
- première catégorie : categorie/nom-cat-A
- seconde catégorie : categorie/nom-cat-B
- ...

Pour être plus clair, ce qui pose problème, c'est qu'on indique a chaque fois un n° dans la première partie de l'url (categorie1, categorie2, ...)

Google n'aime pas ce type de structure... car il n'arrive pas à comprendre la logique de l'arborescence.

Il en va de même pour les articles et pour les pages

Bye.

**Comment by pluxml** [comment]
Bonjour
Le plugin MyBetterUrls permet d'améliorer la forme des urls au niveau SEO
http://pluxopolis.net/myplugins
