### ISSUE TITLE
Supprimer le lien "Nouvel article"

### ISSUE THREAD

**Issue by ghost** [pluxml/PluXml#147]
Un lien "Nouvel article" est présent dans la barre latérale... ce lien n'a pas sa place à ce niveau. Il donne une impression négative... le fonctionnement du CMS semble plus complexe.

À noter qu'aucun lien n'est présent dans la barre latérale pour ajouter une "Nouvelle page".

Bye.

**Comment by pluxml** [comment]
Le lien Nouvel article est un raccourci pour accéder rapidement à une fonctionnalité de base de PluXml qui est de rédiger des articles. Il ne sera pas supprimé.
