### ISSUE TITLE
Donner la possibilité de désactiver certains modules

### ISSUE THREAD

**Issue by ghost** [pluxml/PluXml#149]
Tous les modules ne sont pas forcément utilisés dans un même projet. Il serait intéressant de laisser l'utilisateur choisir quels modules il souhaite utiliser.

Par exemple, s'il veut utiliser que le module "Pages", avoir la possibilité de désactiver le module "Articles" ?

Ainsi, le module "Articles" ne serait plus présent dans la barre latérale, et les dossiers de data ne serait plus présent sur le serveur.

Bye.

**Comment by pluxml** [comment]
PluXml est un moteur de blog avec articles et pages. 
Ce type de personnalisation n'est pas retenu car il ne colle pas à l'orientation du projet
