### ISSUE TITLE
Offrir plus d'options de configuration pour les pages

### ISSUE THREAD

**Issue by ghost** [pluxml/PluXml#150]
Actuellement, les options de configuration pour les pages se limitent à un grand textarea... il serait intéressant de fournir plus d'options, comme la date de création de la page, à quelle autre page elle est liée, ... (voire la page de configuration d'un article)

Bye.

**Comment by pluxml** [comment]
L'ajout de la date de création et de mise à jour de la page est pris en compte pour la v5.5
PluXml ne gère pas les dépendances entre les pages et cette fonctionnalité ne sera pas implémentée
