### ISSUE TITLE
Hook dans la boucle plxShow->lastArtList(...)

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#151]
Plusieurs personnes utilisent lastArtList pour afficher les champs d'une série d'articles dans une page statique. Elles ont souvent aussi besoin d'ajouter des champs dans les fiches articles et de les afficher.
Plusieurs plugins comme artVignette ou chamPlus permettent cela . Et à chaque modification de cette fonction, il faudra corriger ces plugins très populaires.

Comme il n'y a qu'un hook au début de **lastArtList**, ces plugins sont obligés de dupliquer  intégralement lastArtList pour imprimer ces nouveaux champs.

Un hook dans la boucle "**foreach ($aFiles as $v)**", juste avant "**echo $row**" permettrait de modifier la ligne avant de l'afficher.

**Cela ouvrirait d'autres perspectives**.
Imaginons un libraire utilisant Pluxml qui ajoute un champ prix du livre et quantité en stock. 
Il serait facile d'afficher la valeur de son stock en utisant lastArtList.

Notons qu'on ne peut pas afficher le nouveau champ officiel thumbnail. Il me semble utile d'intégrer cette possibilité sans se préoccuper que cela soit un media. Ce point doit se régler dans la chaine de format.

Ce  nouveau champ amène un autre problème. Sa valeur intégre le chemin d'accès au chemin des médias. Or ce chemin est configurable dans Pluxml. Si ce chemin est modifié ou si les datas sont sauvegardés dans un autre dossier, l'affichage des images d'accroche est cassé. Cette remarque est également pour le contenu de l'article. Mais cela est un vieux bug qui traine

**Comment by pluxml** [comment]
Bonjour
Je viens d'ajouter le hook plxShowLastArtListContent dans plxShow::lastArtList()
Je vais regarder également pour les autres points mentionnés.

**Comment by pluxml** [comment]
Concernant le chemin d'accès au chemin médias.
S'il est changé dans les paramètres avancés, le nouveau chemin est bien pris en compte dans le gestionnaires de médias mais aussi au niveau de l'image d'accroche.
On peut donc remplacer sans impact data/medias/ par mondossier/
Je ne vois pas de problème. Peux-tu me donner plus de détails
