### ISSUE TITLE
Support SSL/HTTPS (+ ajout doc ?)

### ISSUE THREAD

**Issue by xila76** [pluxml/PluXml#153]
J'ai voulu activer le SSL/HTTPS sur mon blog avec un certif let's encrypt (même si je pense idem avec auto-signé ou cert payant) et ma conf était pleinement fonctionnel pour accéder à l'admin MAIS sur l'accueil aucuns CSS/JS n'était pris en charge car ils essaient de se charger depuis un HTTP:// alors que je redirige TOUT (via un redirect permanent / https://monblog.com) vers le HTTPS

Comment se fait-il que pluxml censé détecté le protocole HTTP/HTTPS ne le fasse pas correctement dans mon cas de figure ?

Il serait bon d'ajouter dans la doc/faq/wiki (au choix) une façon "clean" d'activer le SSL, car j'ai eu envie de bidouiller ma conf apache mais au final je ne suis parvenu à rien de propre et se taper 20 lignes de ré-écriture d'URL c'est vraiment pas le top :)

Quelqu'un a-t-il déjà réussi à configure un pluxml 5.5 avec SSL ???

**Comment by pluxml** [comment]
Bonjour. Est-ce que tu peux me contacter en privé stp pour échanger sur ce sujet. Merci
http://www.pluxml.org/contact

**Comment by pluxml** [comment]
Pas assez d'informations pour savoir si le problème vient de PluXml ou de la configuration SSL sur l'hébérgeur
