### ISSUE TITLE
Plus de fichier .htaccess -> 404 sur tous les billets

### ISSUE THREAD

**Issue by Mikaciu** [pluxml/PluXml#154]
Depuis le commit https://github.com/pluxml/PluXml/commit/f9c58823a25fdb0af8700a5f592b1deaa342741f qui supprime le fichier htaccess, aucun billet du blog n'est disponible (erreurs 404).
Est-ce un bug, ou alors faut-il changer une configuration ?

**Comment by pluxml** [comment]
Dans l'administration, désactivez, puis réactiver la réécriture d'url. Le fichier .htacces sera récréé.

**Comment by Mikaciu** [comment]
Tout va bien, nickel !
J'ai mis le fichier .htaccess dans le .gitignore, en espérant qu'il soit ignoré par la prochaine mise à jour git.
Merci !
