### ISSUE TITLE
Suppression de plugin:

### ISSUE THREAD

**Issue by Pluxopolis** [pluxml/PluXml#163]
Pluxml regarde s'il existe une fonction onActivate ou OnDeactivate pour le plugin. AMHA, il manque une fonction OnDelete. En effet, certains plugins ont besoin de créer un dossier ou un fichier, qui ne sont pas forcément dans le dossier du plugin (Pb droit en écriture), selon la configuration demandée par l'utilisateur. Quand on supprime le plugin, ces fichiers/dossiers restent.
Les plugins peuvent être installés à la main sans passer par Pluxml, avec des droits en écriture pour l'administrateur du serveur différents des droits accordés au serveur web (typiquement www-data sur Debian et Ubuntu)
Quand on veut supprimer un plugin, Pluxml tente d'abord de supprimer le dossier du plugin. Si ça plante, on arrrête le processus et les fichiers de config et feuilles de style restent en l'état dans le dossier data/configuration.
Dans la fonction plxPlugins::saveConfig(..), il me semble logique de faire dans l'ordre : suppression des feuilles de style, suppression du paramétrage du plugin, mise à jour du fichier data/configuration/plugins.xml et enfin suppression du dossier du plugin dans le dossier plugins.
Hélas, actuellement on procède exactement dans l'ordre inverse.
Quand l'administrateur du serveur veut faire une mise à jour propre, il se retrouve avec les anciennes feuilles de style et l'ancienne config du plugin.

**Comment by bazooka07** [comment]
PR #605 
Dorénavant, il faut désactiver le plugin avant de l'effacer.
