### ISSUE TITLE
Plugins: traduction et langue par défaut

### ISSUE THREAD

**Issue by pluxml** [pluxml/PluXml#167]
Si un plugin n'a pas la traduction correspondant à la langue utilisée dans PluXml, les mots des clés de traduction sont affichés à la place de la traduction. 
=> Utiliser la langue par défaut, afficher un message, prendre par défaut une langue dans le plugin, ....
=> solution à étudier pour palier au problème

**Comment by bazooka07** [comment]
voir pull request plugin_language

**Comment by pluxml** [comment]
Implémenté: https://github.com/pluxml/PluXml/commit/31ba4b8c0a699856f5d4f5b9a045ff4ea787544d
