### ISSUE TITLE
Adaptibilité mobile des commentaire imbriqués

### ISSUE THREAD

**Issue by Draky50110** [pluxml/PluXml#172]
Bonjour.

Petit souci avec les commentaires imbriqués, vu chez Cyrille Borne, sur mon smartphone : au-delà d'un certain nombre de commentaires en réponse au précédent, plus rien ne s'affiche, ça se décale un max.

**Comment by pluxml** [comment]
Bonjour

Confirmé.

Violà un patch à mettre dans le fichier css de son thème pour gérer l'affichage des commentaires sur des petits écrans
```
@media (max-width: 767px) {
	.level-1,
	.level-2,
	.level-3,
	.level-4,
	.level-5,
	.level-max {
		margin-left: 5px;
	}
}
```

**Comment by Draky50110** [comment]
Merci.

Un boulot pour super @cyrborne ça !
