### ISSUE TITLE
Commentaires toujours refusés si capcha=0

### ISSUE THREAD

**Issue by ortolot** [pluxml/PluXml#181]
Bonjour,

En empaquetant la PluXml 5.5 pour Debian, j'ai découvert que, avec `capcha=0` (façon de parler, mais vous comprendrez ce que je veux dire…), les commentaires étaient systématiquement refusés ('La vérification anti-spam a échoué').

Cela vient de `core/lib/class.plx.motor.php:858`, qui vérifie certaines informations liées au capcha, même si celui-ci est désactivé :

```php
                if(strtolower($_SERVER['REQUEST_METHOD'])!= 'post' OR !isset($_SESSION["capcha_token"]) OR !isset($_POST['capcha_token']) OR ($_SESSION["capcha_token"]!=$_POST['capcha_token'])) {
                        return L_NEWCOMMENT_ERR_ANTISPAM;
                }
```

J'ai corrigé cela en testant d'abord `$this->aConf['capcha']` ; vous pourrez trouver ma correction dans http://git.ortolo.eu/pkg-pluxml.git, branche contrib/fix-mandatory-capcha, que vous pouvez récupérer ainsi :

```text
$ git pull git://git.ortolo.eu/pkg-pluxml.git contrib/fix-mandatory-capcha
```

Si vous préférez, voici également un patch, que vous pouvez appliquer ainsi :

```text
$ patch -p1 < fix-mandatory-captcha.patch
```

**Comment by ortolot** [comment]
Bon, en fait GitHub refuse les fichiers dont le nom se termine par {{.patch}}, c'est un comble tout de même… Je vous laisse faire un git pull, ça suffira je pense.

**Comment by ortolot** [comment]
Le code corrigé, ça donne ça : 

```php
		if(strtolower($_SERVER['REQUEST_METHOD'])!= 'post' OR $this->aConf['capcha'] AND (!isset($_SESSION["capcha_token"]) OR !isset($_POST['capcha_token']) OR ($_SESSION["capcha_token"]!=$_POST['capcha_token']))) {
			return L_NEWCOMMENT_ERR_ANTISPAM;
		}
```

**Comment by pluxml** [comment]
merci pour la correction. c'est validé
