### ISSUE TITLE
Bug fonction newCommentaire class.plx.Motor

### ISSUE THREAD

**Issue by pluxml** [pluxml/PluXml#187]
La variable $artId s'est transformée en $idArt (ligne.876)

```
public function newCommentaire($artId,$content) {
  ...
   $idx = $this->nextIdArtComment($idArt);
  ...
}
```

**Comment by mathieu269** [comment]
désolé pour le spam des commit, je me suis de nouveau embrouillé avec les différentes branches, le pull request correct est là pour corriger ce bug : 
https://github.com/pluxml/PluXml/pull/188

d'après le code que j'ai lu, le bug dans l'état actuel à pour effet que la numérotation des commentaire sest globale à tous les articles et cela n'a pas l'air de bloquer quelque chose.
