### ISSUE TITLE
core/lib/functions.js optimisation de l'ajout de tag

### ISSUE THREAD

**Issue by MatthieuQuantin** [pluxml/PluXml#194]
On peut améliorer l'expérience utilisateur en évitant la répétition de l'ajout du même mot clé en complétant la fonction comme suit :

function insTag(where, tag) {
	var formfield = document.getElementsByName(where)['0'];

	var tags = formfield.value.split(', ');
	if (tags.indexOf(tag) != -1) return;

	if(formfield.value=='')
		formfield.value=tag;
	else
		formfield.value = formfield.value+', '+tag;
}

**Comment by pluxml** [comment]
Bonjour.
Je ne comprends pas ce que fait le code. J'ai testé ça ne fonctionne pas.
Je peux toujours ajouter le mot clé

**Comment by MatthieuQuantin** [comment]
imaginons que l'on veuille à partir de la liste des tags ajouter le tag existant "Toto".

Avec le code actuel, à chaque fois que l'on cliquera sur le tag "Toto, il s'ajoutera dans l'input des tags de l'article.

En ajoutant dans la fonction, le split et l'indexOf, et avec la même manipulation que ci dessus, un tag ne pourra être présent qu'une fois dans l'input des tags de l'article

**Comment by pluxml** [comment]
Ok compris maintenant. L'info qu'il me manquait c'était l'ajout d'un tag en cliquant sur le lien d'un tag (et pas une saisie manuelle directement dans la zone texte).
c'est tout bon, ça fonctionne.
