### ISSUE TITLE
Suppression des données EXIF après redimensionnement des images.

### ISSUE THREAD

**Issue by cfdev** [pluxml/PluXml#197]
Les données exif des images sont supprimées lors du redimensionnement.
Ce qui empêche des manipulations par la suite sur ces données, typiquement la rotation d'image.

Exemple de fichier:
https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_6.jpg

**Comment by pluxml** [comment]
Redimensionner les images sans perdre les données EXIF implique d'utiliser des librairies dédiées souvent assez lourdes. Si une solution simple existe pouvant se greffer sur ce qui existe dans PluXml, alors ok. Sinon Il faudra envisager de retravailler les images avec des logiciels (photoshop ou autres) avant d'uploader les images sur son site.
