### ISSUE TITLE
Plugin detection

### ISSUE THREAD

**Issue by ouafnico** [pluxml/PluXml#200]
Hello

Il semblerait que si un plugin fraîchement décompressé dans le dossier plugins, contient des caractères spéciaux il n'est pas détecté.
J'ai testé avec plxMyContact ou plxMyPluginDownloader, tant que le dossier dézippé possédait le "-version" il ne s'affichait pas.

C'est peut-être normal, mais ça mériterait d'être ajouté sur le wiki.

**Comment by pluxml** [comment]
Bonjour
Effectivement le nom des dossiers des plugins doivent respectés certaines conventions propre à PluXml pour être reconnu.
