### ISSUE TITLE
Suggestion : rendre la mise en ligne de vidéo accessible à des non codeurs

### ISSUE THREAD

**Issue by luffah** [pluxml/PluXml#202]
Dans PluXml, on peut ajouter autant des vidéos que des images dans les médias.
Cependant on dirait qu'il n'y a rien de prévu (même avec les plugins ckeditor) pour ajouter des vidéos sans taper dans du code source html (et en pateaugeant avec les url possibles).

D'autres part lorsqu'on ajoute des vidéos ou des images, une petite croix rouge apparait à sa gauche laissant penser que le transfert a été un échec bien que ce dernier ait réussi. 

Je pense que c'est un point assez bloquant pour un CMS moderne de ne pas pouvoir laisser facilement la possibilté d'ajouter une vidéo  ou une musique.  
En tout cas, une intégration des vidéos similaire à celle des images faciliterait la vie de personnes souhaitant mettre en ligne des tutos, et autres présentations.

Les parties concernées semblent être l'explorateur de média et interface d'édition de page
Merci d'avance aux personnes courageuses souhaitant s'atteler à cette tâche.

**Comment by pluxml** [comment]
Les outils comme ckeditor et autres editeurs ont de quoi intégrer facilement le code pour afficher des videos
