### ISSUE TITLE
Suppression sans confirmation des utilisateurs et des pages statiques

### ISSUE THREAD

**Issue by Sbgodin** [pluxml/PluXml#208]
Sur la version actuelle (e8d2b52) on peut supprimer sans confirmation des utilisateurs et des pages statiques.

Pour ce faire, aller dans la page dédiée :
- choisir un utilisateur (resp. une page statique)
- dans la liste déroulante choisir « Supprimer »
- cliquer sur « Modifier la liste des utilisateurs » (resp. « Modifier la liste des pages statiques »)
- la suppression se fait sans demander de confirmation

En principe, quand on supprime il faut cliquer sur le bouton « Ok » et confirmer le choix. L'appui sur l'autre bouton contourne la confirmation. Les deux boutons soumettent le formulaire mais seul le premier demande confirmation.

**Comment by pluxml** [comment]
Bonjour

La suppression dans PluXml se fait par
1. choisir un utilisateur (resp. une page statique)
2. dans la liste déroulante choisir « Supprimer »
3. cliquer sur le bouton « Ok »

Le bouton "Modifier la liste des utilisateurs" ne sert pas à la suppression mais a enregistrer les modifications des données (cf manuel utilisateur)

**Comment by Sbgodin** [comment]
Pardon d'insister, mais il est possible de supprimer un utilisateur sans demande de confirmation. Il suffit de se tromper de bouton, or le message de suppression est censé empêcher cela.

**Comment by pluxml** [comment]
Je vais controler tout ça alors.
Merci

**Comment by pluxml** [comment]
Je confirme le probleme. Je prends en compte les corrections nécessaires.
Encore merci d'avoir insister :+1:

**Comment by Sbgodin** [comment]
À ton service 😃 PluXml est vraiment bon à l'usage, avec un code bien écrit.
