### ISSUE TITLE
plxUtils::testModRewrite renvoie true même si le serveur n'est pas Apache

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#218]
dans la fonction testModRewrite, on teste la présence de la fonction apache_get_modules.
Si elle n'existe pas, par exemple pour un serveur Nginx, testModRewrite renvoie true quand même

Rappelons que ModRewrite est une spécialité indienne et qu'on procède autrement sur des serveurs Nginx ou Lighttpd qui sont fréquemment utilisés sur des RaspberryPi et autres sbc.

**Comment by pluxml** [comment]
Le libellé affiché par testModRewrite est "Module apache de réécriture d'url mod_rewrite disponible".
Il n'y a donc pas d'ambiguité sur ce qui est testé par rapport à un autre type de serveur.
Si tu sais connais codé un équivalent pour nginx ou Lighttpd, je suis preneur. Merci
