### ISSUE TITLE
Encodage des fichiers

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#221]
La plupart des fichiers de PluXml ont basculé en encodage **UTF-8**. C'est une bonne chose.
Certains sont restés en ASCII pur
Plus gênant il reste encore un fichier en **ISO-8859** :
`
foo@mymachine.$ file */*/* | grep 8859
core/lib/class.plx.motor.php:           PHP script, ISO-8859 text, with CRLF line terminators
`
Quelques commandes sous Linux dans le dossier de PluXml comme "**file \*/\*/\***" ou "**file \*/\***" ou "**file \***", éventuellement complétés par " **| grep 8859**" permettent de voir cela.

Dans une moindre mesure, il y a une grande hétérogéniiété sur les fins de ligne **CRLF** et **LF**.
On pouvait harmoniser tout cela assez facilement avec un éditeur de texte comme Geany ou Notepad++

**Comment by sudwebdesign** [comment]
C'est fait

**Comment by bazooka07** [comment]
Pour uniformiser les fins de ligne , se placer dans le dossier de PluXml et faire :
dos2unix core/lang/*/*
dos2unix core/lib/*
....

**Comment by sudwebdesign** [comment]
@bazooka07 Merci du tuyau

**Comment by pluxml** [comment]
fichiers convertis au format unix avec la commande:
`find . -type f -print0 | xargs -0 dos2unix`
