### ISSUE TITLE
Page d'authentification

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#225]
Côté admin de PluXml, toutes les pages ont un **attribut id** dans leur balise &lt;body id="..."&gt...&lt;/body&ht, généré par le script core/admin/top.php.
Oui, toutes sauf une : **core/admin/auth.php** qui n'"inclue" pas core/admin/top.php.
C'est dommage car je souhaite avoir une différenciation visuelle forte avec les autres pages de l'admin.
Certes, il y a toujours moyen de contourner l'obstacle en ajoutant dans une feuille  personnalisée pour l'admin, une règle comme ceci : 
`body:not([id]) {
	background-color: #000;
}`

Autre souci: les feuilles de style des plugins ne sont pas prises en compte sur cette page.

**Comment by pluxml** [comment]
Je rajouterai l'id sur la page auth.php. c'est un oubli tout simplement
Merci
