### ISSUE TITLE
C'est possible un menu collant

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#226]
Voir la discussion ici :
http://forum.pluxml.org/viewtopic.php?pid=54107

et de remplacer dans le fichier header.php du thème par défaut
&lt;?php $plxShow->lang('MENU'); ?&gt;
par l'entité HTML: **&amp;#9776;** (un burger est internationnellement reconnaissable)

**Comment by jerrywham** [comment]
Lire également : http://www.a11ymatters.com/pattern/mobile-nav/

**Comment by pluxml** [comment]
classe css .sticky disponible avec PluCSS 1.3
affichage burger pris en compte par PluCSS

**Comment by bazooka07** [comment]
La dernière fois que j'ai eu accès à un Mac, sitcky ne fonctionnait pas avec.
D'après la littérature (MDN ?), il faut écrire la règle avec le préfixe vendeur :
```
.nav {
  ...
  position: -web-sticky;
  position: sticky;
}
```
J'ai fait la modif sur le site suivant mais je n'ai pas eu l'occasion de refaire un test sur Mac :
http://kazimentou.fr
Et pour Edge, il va falloir attendre

**Comment by pluxml** [comment]
je suis sur mac est `position: sticky;` fonctionne bien avec FF
je testerai avec d'autres navigateurs
je vais compléter la règle css avec  `position: -web-sticky;`
merci
