### ISSUE TITLE
droits des fichiers dans core/lib

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#228]
Dans le dossier core/lib, le fichier class.plx.show.php est le seul à avoir des droits d'execution.
A unifier

**Comment by pluxml** [comment]
Quelle commande recommandes-tu pour unifier les droits ?

**Comment by bazooka07** [comment]
`sudo chmod a-x core/*/*.*`

Pour trouver les fichiers executables :
```
find core -perm /u=x,g=x,o=x -type f -exec ls -l {} \;
find theme -perm /u=x,g=x,o=x -type f -exec ls -l {} \;
```

Mon côté paranoîaque m'incite à faire ceci :
```
sudo chmod -R o-wx core
sudo chmod -R o-wx theme
sudo chmod -R ug+w *
sudo chown -R www-data:www-data *
```
www-data est le compte sous lequel tournent Apache et Nginx avec Debian/Ubuntu
Si on se connecte sous le compte foo, faire ceci pour éviter les tracasseries avec un éditeur ou un client ftp :
`sudo usermod -aG www-data foo`

**Comment by pluxml** [comment]
excellent. merci
