### ISSUE TITLE
Désactiver les flux rss

### ISSUE THREAD

**Issue by pluxml** [pluxml/PluXml#232]
Ajouter la possibilité de désactiver (temporairement) les flux rss à partir d'une case à cocher pour éviter d'avoir à renommer le fichier feed.php

**Comment by Philippe-M** [comment]
https://github.com/pluxml/PluXml/pull/335

**Comment by P3ter** [comment]
Merci beaucoup pour la PR !

Dans le commit [ca35acc ](https://github.com/pluxml/PluXml/commit/ca35acc15262eb171ff9c35d52f1efca5c281931), je propose néanmoins d'inverser le paramètre pour le changer de "_Désactiver l'affichage des flux RSS_" à "_Afficher les flux RSS_", car pour tous les paramètres disponibles dans l'admin c'est géré dans ce sens.

J'ai retiré le test fait sur la vue (sauf pour footer.php) pour le réaliser dans le modèle (class.plx.show.php). Ça permet de faire fonctionner cette nouvelle option sur tous les thèmes existant sans modification, mais ce n'est pas parfait : 
* ça ne prend pas en compte le footer (le test est sur la vue)
* lorsqu'on désactive l'affichage des flux RSS, on aura des balises HTML vides (`<span></span>`, `<p></p>`).

Qu'en penses-tu ?

**Comment by Philippe-M** [comment]
Je n'avais pas vu ton commit, la prochaine fois je regarderais avant de me lancer dans le code :)

Lorsque j'ai codé ça je n'ai pas trop prêter attention à la logique côté admin mais ton choix est plus pertinant et ne perdra pas l'utilisateur. En fait je suis d'accord avec toi pour tout sauf pour le dernier point : les balises html vides.

Pour moi cela créé 3 problèmes :

- alourdi (de façon négligeable) la quantité de code et du coups le poids de la partie html transféré au visiteur;
- complexifie le débogage pour un intégrateur/créateur de thème;
- sans être expert, cela doit avoir un impact sur l'accessibilité.

Je vois pas trop comment gérer ça avec la séparation de la vue et du code php :(

**Comment by jerrywham** [comment]
Bonjour,
Je trouve dommage de diminuer encore plus la lisibilité des flux rss en les désactivant par défaut. 
Beaucoup ne les ré-activeront pas par méconnaissance.
On se prive d'un bel outil au profit à nouveau des GAFAM.

**Comment by sudwebdesign** [comment]
Il suffit juste qu'ils soient actifs a l'installation et lors de la future MAJ.

**Comment by sudwebdesign** [comment]
@P3ter : Petit truc en aparté, règle l'indentation de ton éditeur [actuellement il semble qu'il utilise les espaces](https://github.com/pluxml/PluXml/blob/ca35acc15262eb171ff9c35d52f1efca5c281931/core/lib/class.plx.show.php#L863)

J'affiche aussi les caractère non imprimable (et parfois c'est l'horreur), il efface les espace de fin de ligne.
ps: en général remplacer 4 espaces par une tabulation ds tous le doc, parfois la session avec geany ;) rétabli la situation.

**Comment by P3ter** [comment]
> Je trouve dommage de diminuer encore plus la lisibilité des flux rss en les désactivant par défaut.

@jerrywham, pas de panique, ils sont affichés par défaut à l'installation ou à la mise à jour ;-)

@Philippe-M, le commit que j'ai mis en lien, je l'ai réalisé à partir de ta branche, j'ai repris ton code et fais mes modifications dessus. Pour les balises HTML vides, je ne vois pas d'autres solutions que d'ajouter aux fonctions `artFeed`, `comFeed` et `tagFeed`, une variable `$format` en paramètre comme pour les autres fonctions de $plxShow.

@sudwebdesign,  j'ai pris note de ta remarque, merci. Effectivement j'ai quelques soucis de formatage, mais ça devrait aller mieux pour les prochaines fois.

**Comment by sudwebdesign** [comment]
@P3ter +1 pour les $format & reste compatible avec les anciens thèmes :)

**Comment by Philippe-M** [comment]
@P3ter : nikel la variable $format. Je pensais faire des tests lundi en arrivant au boulot avec cette idée et je vois que tu m'a devancé ;)

**Comment by P3ter** [comment]
J'ai mergé tout ça dans la branche develop (PluXml 5.8).
Merci à tous !
