### ISSUE TITLE
Accès en écriture du dossier racine pour les thèmes

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#239]
Contrairement au dossier pour les plugins, il n'a pas vérification, dans le script
core/admin/parametres_infos.php,
que le dossier des thèmes PLX_ROOT.$plxMotor->aConf['racine_themes'] est accessible en écriture.

Donc, cela risque d'être compliqué pour modifier le thème en cours avec PluXml.

**Comment by pluxml** [comment]
implémenté
