### ISSUE TITLE
Ajout d'une catégorie depuis l'édition d'article

### ISSUE THREAD

**Issue by F4HFQ** [pluxml/PluXml#244]
Bonjour,

La création d'une nouvelle catégorie depuis la page d'édition/ajout d'un article ne créé pas une nouvelle catégorie mais modifie la dernière créée.

PluXML V5.6

**Comment by pluxml** [comment]
Bonjour.
Je n'arrive pas à reproduire/constater le problème décrit.
Peux-tu donner plus de détail et comment reproduire le probleme.
Merci

**Comment by nIQnutn** [comment]
depuis /core/admin/article.php
l'ajout d'une nouvelle catégorie à modifier une autre.
obligé de renommer puis recréer la catégorie depuis /core/admin/categories.php 

la catégorie modifiée correspond à l'Id le plus élevé.

**Comment by sudwebdesign** [comment]
Cela arrive lorsque la limite des catégories est atteinte, au final c'est toujours la dernière qui est modifiée lors d'une création.

@F4HFQ & @nIQnutn :
Quel sont vos derniers identifiants de catégorie?  99?

**Comment by nIQnutn** [comment]
non, c'est pas ça et c'est pas la première fois que ça m'arrive.
pour info, la dernière catégorie a pour id 16
