### ISSUE TITLE
Erreur dans le Guide du développeur

### ISSUE THREAD

**Issue by luffah** [pluxml/PluXml#247]
Salut !

dans le guide du développeur (fournis par votre site) page 48-49, 
il est indiqué d'utiliser le hook 'plxAdminEditCategory', cependant dans class.plx.admin.php:561
le hook appelé est 'plxAdminEditCategorie'.

Un petit bug comme celui ci peut être génant en terme de développement et de compatibilté de plugin.

Bonne journée

**Comment by P3ter** [comment]
Corrigé dans la nouvelle version du wiki (https://wiki.pluxml.org) via le commit https://github.com/pluxml/PluXml-Wiki/commit/3938a6fdc3f9908b5068dee60fd19cb0d9432edb)
