### ISSUE TITLE
L'URL n'est pas rempli automatiquement si l'article en langue russe (cyrillique)

### ISSUE THREAD

**Issue by KonstantinFromRussia** [pluxml/PluXml#248]
Salut!
Lors de la création d'articles en russe, c'est-à-dire en cyrillique (qui est inclus dans la livraison standard du système), le champ de l'URL n'est pas rempli automatiquement. Au lieu de cela, l'entrée **"new-article"** apparaît dans le champ URL. Et cela se produit lorsque vous créez chaque nouvel article.
Avec d'autres langues, tout fonctionne bien, l'URL est remplie selon le titre de l'article. Mais pas avec le nom russe :(

**Comment by jerrywham** [comment]
Voir la discussion sur le forum http://forum.pluxml.org/viewtopic.php?pid=55342#p55342
Cela vient du fichier lang/ru/admin.php dont il manque certaines traductions (lignes 41, 42 et 43) :
'L_DEFAULT_NEW_CATEGORY_URL'		=> 'new-category',
'L_DEFAULT_NEW_STATIC_URL'		=> 'new-page',
'L_DEFAULT_NEW_ARTICLE_URL'		=> 'new-article',

**Comment by jerrywham** [comment]
Est-ce que ces traductions sont bonnes ?
'L_DEFAULT_NEW_CATEGORY_URL'		=> 'новая-категория',
'L_DEFAULT_NEW_STATIC_URL'		=> 'новая-страница',
'L_DEFAULT_NEW_ARTICLE_URL'		=> 'новая-статья',

**Comment by jerrywham** [comment]
Aïe : il y a un problème d'encodage et de nom de fichier lorsque l'on utilise le cyrillique dans les urls. Donc mon pull request ne va pas

**Comment by jerrywham** [comment]
J'ai proposé un pull request supplémentaire qui modifie les méthodes title2url et title2filename car cela poser des problèmes d'encodage.
Par contre, les url en cyrillique sont du style "index.php?article25/03-2-ab0bl8"

**Comment by pluxml** [comment]
@jerrywham en lisant ton dernier commentaire dois-je en déduire que ton PR créer des effets de bords ? Si c'est le cas je ne peux pas le valider

**Comment by jerrywham** [comment]
Oui malheureusement. Bazooka a proposé une solution meilleure que la mienne.

**Comment by P3ter** [comment]
Done in PluXml 5.8.
