### ISSUE TITLE
Information Disclosure: Password file publicly accessible

### ISSUE THREAD

**Issue by ProDigySML** [pluxml/PluXml#252]
The file that holds all user hashes and salts is publicly accessible. The path to the file is:
`<web path>/data/configuration/users.xml`

Visiting this page from a browser gives all user's password hashes and salts. I would advise having a .htaccess file stopping the viewing of such files.

**Comment by Pluxopolis** [comment]
A .htaccess file is already present in data/configuration/ with these rules

```
<Files *>
	Order allow,deny
	Deny from all
</Files>

```
If the file is not there in your folder, check your installation. It should be there.
users.xml is protected as all files in this directory

**Comment by ProDigySML** [comment]
Interesting... Something must have gone wrong with my installation then. I don't seem to have a .htaccess file in the data/configuration directory

**Comment by Pluxopolis** [comment]
maybe files starting with . character like .htaccess are hidden in your editor

**Comment by ProDigySML** [comment]
Apologies. Turns out something went wrong with the installation. This bug is invalid.
