### ISSUE TITLE
plxMotor::urlRewrite($url) et adresse absolue

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#258]
Si le paramètre &dollar;url est une adresse absolue, par exemple :
https://farm4.staticflickr.com/3690/9462214204_563aa1fc49_m.jpg
alors le résultat de la fonction est :
http://test.lan/PluXml-2017/https#://farm4.staticflickr.com/3690/9462214204_563aa1fc49_m.jpg
en supposant que l'adresse du site soit http://test.lan/PluXml-2017.

Cas d'utilisation : la vignette d'un article peut-être hébergé sur un autre serveur et servir à afficher une image plus grande avec des plugins comme zoombox, colorbox, ....

Avant de traiter la requête, il faut vérifier qu'on n'est pas en présence d'une adresse absolue en testant &dollar;url avec l'expression régulière:
@^[a-z]+://@

Il y a également un problème si l'url de la vignette est du type data:image/..:base64.

**Comment by pluxml** [comment]
#279
