### ISSUE TITLE
Catégorie: "non classé"

### ISSUE THREAD

**Issue by nIQnutn** [pluxml/PluXml#260]
Si on n'assigne pas de catégorie à un article, on se retrouve par défaut avec le libellé "non classé"
quand on publie l'article, ce libellé est correctement affiché.
par contre, si on prévisualise l'article, c'est vide.
pour les tags, il y a bien "aucun" pour la prévisualisation et quand l'article est publié.

rien de grave.

**Comment by pluxml** [comment]
corrigé
