### ISSUE TITLE
ajouter le format gpx

### ISSUE THREAD

**Issue by pluxml** [pluxml/PluXml#280]
Ajouter le format gpx (traces gps) au gestionnaire de médias dans la liste des extensions autorisées (upload des fichiers)

**Comment by P3ter** [comment]
Ajouter également le format webp : https://forum.pluxml.org/viewtopic.php?pid=58836#p58836

**Comment by P3ter** [comment]
Formats gpx, bmp et webp ajouté à PluXml.
**Attention** : la création de miniatures .bmp ne fonctionne qu'à partir de PHP 7 et de PHP 7.1 pour .webp.
