### ISSUE TITLE
Forgot Admin Password in Pluxml CMS

### ISSUE THREAD

**Issue by AlexL777** [pluxml/PluXml#285]
Hello Developers,

I have a small problem, so I forgot the admin password.

Unfortunately, I can not find a tool that generates a password from the MD5 password + salt.

It just does not work.

Thanks in Advance.

**Comment by bazooka07** [comment]
Hello,
You must proceed a new install of PluXml in a separate folder.
Proceed as normal. After that, with an editor open the "data/configuration/users.xml" file.
Look for the user with profil equals to 0. He's the administrator profil.
Copy the values from password and salt fields and paste them in your current PluXml.
It's the official way for retrieving access for PluXml.
An alternative way is to email address and add the lostPassword plugin to PluXml before forgetting your password. With it a random password is sent to the email address matching with login.
For downloading this plugin : https://kazimentou.fr/pluxml-plugins2/index.php?plugin=lostPassword&download
German translation will be appreciate for this plugin.

**Comment by AlexL777** [comment]
Ok, thanks for your quick help. It helped me alot. I was able to log in again as an admin. Problem solved.
