### ISSUE TITLE
Broken RSS feed with plugin

### ISSUE THREAD

**Issue by ghost** [pluxml/PluXml#288]
C'est pas la première fois mais il est possible d'avoir un flux RSS invalide à cause d'un plugin (même fonctionnel).
C'est pas très intuitif et c'est générallement pas la première chose qu'on teste lorsque qu'on utilise un plugin. 
Un correctif serait apprécié pour éviter d'avoir des erreurs à cause de simple espaces.

exemple:
https://github.com/nIQnutn/plxMySocialNetwork/commit/257671981e0bca751a91147b3c66a104c24fa444

**Comment by bazooka07** [comment]
Broken link !
