### ISSUE TITLE
Sécurité: Externaliser les éléments javascripts et css

### ISSUE THREAD

**Issue by mirabellette** [pluxml/PluXml#292]
Bonjour,

Il y a plusieurs éléments javascript et css directement dans les pages html/php de PluXml. Ce n'est pas une bonnes pratique de développement et ces élements rentrent en conflit avec les Content Security Policies qu'appliquent le serveur web.

Pour trouver les éléments, il faut faire : 

- grep -R "style=" core/ pour les fichiers qui possèdent des éléments de style directement le code html/php au lieu d'être externalisé dans le fichier style.css

- grep -R "<script>" core/ pour les fichiers qui possèdent du javascript présent dans le code html/php au lieu d'être externalisé dans un fichier javascript dédié

**Comment by mirabellette** [comment]
J'aurai bien pris le temps de faire une pull request mais j'ai l'impression qu'elles ne sont pas validées donc je vais attendre un peu que le développeur de PluXML (que je remercie pour son immense travail) ait du temps de disponible.

**Comment by Philippe-M** [comment]
Bonjour, je m'incruste dans la conversation. Juste mon point de vue par rapport à ton manque de temps qui me parait totalement justifié (puisque c'est du perso). Dans ce cas pourquoi ne pas délégué cette partie à un autre membre actif ? C'était juste une proposition qui déborde du sujet de ce ticket ;)

**Comment by mirabellette** [comment]
Une idée pourrait être de rédiger une documentation vis-à-vis des pull request. Par exemple en demandant de réduire une pull request à une seule fonctionnalité. Développement qui doit induire le moins de refactoring possible. 

Cette solution pourrait être temporaire en attendant que tu aies plus de temps pour t'y consacrer ou qu'une personne décide de forker le projet et de le reprendre en main véritablement.

A garder en mémoire que le mieux et l'ennemi du bien.

**Comment by Thatoo** [comment]
J'ai fait une pull request ici pour aider un peu sur la question : https://github.com/pluxml/PluXml/pull/476
J'ai aussi travaillé sur kzcontacts et share_me.
L'ideal serait de pouvoir regrouper les js des plugins en un seul js minimisé comme c'est le cas pour les css des plugins aujourd'hui, non?

**Comment by P3ter** [comment]
Merci pour la PR, je regarde dès que possible.
Pour la concaténation des JS, je n'ai rien contre, au contraire ça réduirait le nombre d’interactions avec le serveur ce qui est mieux pour la webperf. Je le note pour une prochaine version de PluXml, merci pour l'idée.
