### ISSUE TITLE
Image d'article, afficher une vignette

### ISSUE THREAD

**Issue by Philippe-M** [pluxml/PluXml#296]
Bonjour, 

J'ai fais une petite modification dans le fichier class.plx.show.php. Cette modification permet d'afficher la vignette d'une image d'article au lieu de la version en grande taille redimensionner par css.

```
	public function artThumbnail($format='<img class="art_thumbnail" src="#img_url" alt="#img_alt" title="#img_title" />', $echo=true) {

		$imgUrl = $this->plxMotor->plxRecord_arts->f('thumbnail');
		if($imgUrl) {
			$row = str_replace('#img_url', $this->plxMotor->urlRewrite($imgUrl), $format);
			$row = str_replace('#img_title', plxUtils::strCheck($this->plxMotor->plxRecord_arts->f('thumbnail_title')), $row);
			$row = str_replace('#img_alt', $this->plxMotor->plxRecord_arts->f('thumbnail_alt'), $row);
			if($echo)
				echo $row;
			else
				return $row;
		} else {
			if(!$echo) return false;
		}

	}
```

Par 

```
	public function artThumbnail($format='<img class="art_thumbnail" src="#img_url" alt="#img_alt" title="#img_title" />', $echo=true, $thumb=true) {

		$imgUrl = $this->plxMotor->plxRecord_arts->f('thumbnail');
		if($imgUrl) {
			if($thumb) {
				$filename = parse_url($imgUrl);
				$filename = basename($filename['path']);
				$thumbfile = plxUtils::thumbName($filename);
				$imgUrl = str_replace($filename, $thumbfile, $imgUrl);
				$row = str_replace('#img_url', $this->plxMotor->urlRewrite($imgUrl), $format);
			} 
			$row = str_replace('#img_url', $this->plxMotor->urlRewrite($imgUrl), $format);
			$row = str_replace('#img_title', plxUtils::strCheck($this->plxMotor->plxRecord_arts->f('thumbnail_title')), $row);
			$row = str_replace('#img_alt', $this->plxMotor->plxRecord_arts->f('thumbnail_alt'), $row);
			if($echo)
				echo $row;
			else
				return $row;
		} else {
			if(!$echo) return false;
		}

	}
```

**Comment by jerrywham** [comment]
Il vaudrait mieux écrire 
```php
public function artThumbnail($format='<img class="art_thumbnail" src="#img_url" alt="#img_alt" title="#img_title" />', $echo=true, $thumb=true) {

		$imgUrl = $this->plxMotor->plxRecord_arts->f('thumbnail');
		if($imgUrl) {
			if($thumb) {
				$filename = parse_url($imgUrl);
				$filename = basename($filename['path']);
				$thumbfile = plxUtils::thumbName($filename);
				$imgUrl = str_replace($filename, $thumbfile, $imgUrl);
				$row = str_replace('#img_url', $this->plxMotor->urlRewrite($imgUrl), $format);
			} 
			$row = str_replace(
                                  array(
                                          '#img_url',
                                          '#img_title',
                                          '#img_alt'
                                  ), 
                                  array(
                                          $this->plxMotor->urlRewrite($imgUrl),
                                          plxUtils::strCheck($this->plxMotor->plxRecord_arts->f('thumbnail_title')),
                                          $this->plxMotor->plxRecord_arts->f('thumbnail_alt')
                                  ), 
                       $format);
			if($echo)
				echo $row;
			else
				return $row;
		} else {
			if(!$echo) return false;
		}

	}
```

**Comment by bazooka07** [comment]
Je vois plus les choses comme ceci :
```php
<?php`
/* --------- plxShow::artThumbnail() ---------- */
public function artThumbnail($format='<a href="#img_url"><img class="art_thumbnail" src="#img_thumb_url" alt="#img_alt" title="#img_title" /></a>', $echo=true) {
    $filename = trim($this->plxMotor->plxRecord_arts->f('thumbnail'));
    if(!empty($filename)) {
        $img_url = $this->plxMotor->urlRewrite($filename);
        $img_thumb = plxUtils::thumbName($filename);
        $replaces = array(
            '#img_url'      => $img_url,
            '#img_thumb_url'=> (file_exists(PLX_ROOT.$img_thumb)) ? $this->plxMotor->urlRewrite($img_thumb) : $img_url,
            '#img_title'    => plxUtils::strCheck($this->plxMotor->plxRecord_arts->f('thumbnail_title')),
            '#img_alt'      => $this->plxMotor->plxRecord_arts->f('thumbnail_alt')
        );
        if($echo)
            echo str_replace(array_keys($replaces), array_values($replaces), $format);
        else
            return str_replace(array_keys($replaces), array_values($replaces), $format);;
    } else {
        if(!$echo) return false;
    }
}
?>
```
On pourra corriger aussi plxUtils::thumbName() :
```php
<?php
/* -------- plxUtils::thumbName($filename) -------- */
	public static function thumbName($filename) {
		if(preg_match('/^(.*\.)(jpe?g|png|gif)$/iD', $filename, $matches)) {
			return $matches[1].'tb.'.$matches[2];
		} else {
			return $filename;
		}
	}
?>
```
Et si vous préférez sous forme de Gist
https://gist.github.com/bazooka07/5d1821030f37a0d430dd6b561a10e508

**Comment by jerrywham** [comment]
Ce n'est pas un comportement optimal car tu fais intervenir deux fonctions au lieu de lire des tableaux.

**Comment by Philippe-M** [comment]
Je trouve la version de @jerrywham plus facile à lire

**Comment by pluxml** [comment]
La version de @bazooka07 est très élégante dans l'utilisation de #img_thumb_url.
J'aurais également proposé une version avec cette nouvelle variable qui laisse plus de liberté dans le formatage coté thème, et qui évite aussi un 3ieme paramètre d'appel dans la méthode artThumbnail.
En revanche je suis plus réservé sur l'utilisation des array_keys et array_values alors qu'il suffirait d'avoir juste 2 arrays et de les utiliser comme l'a fait @jerrywham dans son str_replace. ça me semble plus optimal.

**Comment by bazooka07** [comment]
@Philippe-M ,
Si la vignette n'existe pas on affiche l'image en taille réelle ($img_url). L'intérêt de cette variable est d'éviter d'évaluer $this->plxMotor->urlRewrite($filename) une deuxième fois.

@jerrywham ,@pluxml,
L'intérêt d'avoir un seul tableau est d'avoir un code plus lisible. On fait plus facilement la corrélation entre le motif de recherche et sa valeur de remplacement. Quand on doit y revenir plusieurs mois après, cela peut aider.
Dans le cas de l'emploi de 2 tableaux, il faut s'assurer qu'ils aient le même nombre d'éléments et que l'ordre est le même pour chacun.
En temps d'exécution, l'impact doit être négligeable

**Comment by jerrywham** [comment]
Si le code est présenté comme je l'ai fait, tu vois de suite la correlation entre les lignes. 3 lignes d'un côté, 3 lignes de l'autre. Ce n'est pas excessivement difficile à vérifier.
Concernant l'impact, c'est sûr que sur une seule fonction, c'est négligeable. Mais ça, répéter plusieurs fois, plus une autre fonction dans le même accabit à une autre endroit et on a vite fait de sortir les rames, surtout sur des config mutualisées...

**Comment by pluxml** [comment]
@bazooka07 

> Dans le cas de l'emploi de 2 tableaux, il faut s'assurer qu'ils aient le même nombre d'éléments et que l'ordre est le même pour chacun.

Faux argument. Le code c'est toi qui l'écrit et qui le valide. Donc tu sais exactement combien il faut d’éléments, et comme ça fait partie du core de PluXml personne n'y touchera après. A part ce détail c'est tout bon le code que tu proposes

@jerrywham +1

**Comment by bazooka07** [comment]
On peut contourner le problème comme ci-dessous mais c'est moins agréable à lire et il n'y a que 4 entrées :
```php
$result = str_replace(
    array(
        '#img_url',
        '#img_thumb_url',
        '#img_title',
        '#img_alt'
    ),
    array(
        $img_url, // #img_url
        (file_exists(PLX_ROOT.$img_thumb)) ? $this->plxMotor->urlRewrite($img_thumb) : $img_url, // #img_thumb_url
        plxUtils::strCheck($this->plxMotor->plxRecord_arts->f('thumbnail_title')), // #img_title
        $this->plxMotor->plxRecord_arts->f('thumbnail_alt') // #img_alt
    ),
    $format
);
if($echo)
    echo $result;
else
    return $result;
```
Pourquoi $row ?

**Comment by pluxml** [comment]
@bazooka07 je préfère de loin cette syntaxe :+1:

**Comment by Philippe-M** [comment]
@bazooka07, @jerrywham, @pluxml 
`Si la vignette n'existe pas on affiche l'image en taille réelle ($img_url). L'intérêt de cette variable est d'éviter d'évaluer $this->plxMotor->urlRewrite($filename) une deuxième fois.`

`et qui évite aussi un 3ieme paramètre d'appel dans la méthode artThumbnail.`

Il faut laisser le choix à l'administrateur et/ou créateurs de thèmes d'utiliser la vignette ou la taille réelle.

**Comment by bazooka07** [comment]
Outdated !
