### ISSUE TITLE
Plus de traduction pour les plugins

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#307]
dans core/lib/cplass.plx.plugins, à la ligne #492, on a cette instruction
`include '$filename';`
Donc la variable n'est plus interprêtée avec les simples quotes.
**A corriger rapidement**
Voir PR suivant :
https://github.com/pluxml/PluXml/pull/306

**Comment by P3ter** [comment]
My bad un commit resté en local, que j'ai oublié de push.
