### ISSUE TITLE
L_SUNDAY jamais retourné dans date

### ISSUE THREAD

**Issue by jerrywham** [pluxml/PluXml#322]
Dans le fichier /core/lib/class.plx.date.php
```php
	public static function getCalendar($key, $value) {
		if(!$value) return false;
(...)
```
Si `$value == 0`, la fonction le considère comme `null` avec cette formulation, ce qui fait que les index en 0 (notamment `L_SUNDAY`) ne peuvent jamais être retournés.
De plus, je ne pense pas que cette ligne soit pertinente car la méthode exige 2 variables (et donc si la variable `$value` n'est pas renseignée, cela soulèvera une erreur).

Je propose donc de mettre la ligne suivant à la place :
```php
	public static function getCalendar($key, $value) {
		if(!$value) $value = 0;
(...)
```

**Comment by P3ter** [comment]
Hello,

Finalement est-ce qu'il ne serait pas mieux d'utiliser la fonction isset() ? 

```
public static function getCalendar($key, $value) {
   if(!isset($value)) return false;
   (...)
}
```
Source : https://www.php.net/manual/fr/function.empty.php
Voir l'exemple 1 : 

```
$var = 0;
                   
// Evalué à vrai car $var est vide
if (empty($var)) {
  echo '$var vaut soit 0, vide, ou pas définie du tout';
}
                   
// Evalué à vrai car $var est défini
if (isset($var)) {
  echo '$var est définie même si elle est vide';
}
```

**Comment by jerrywham** [comment]
La méthode exige 2 variables et donc si la variable $value n'est pas renseignée, cela soulèvera une erreur. Donc il n'est pas nécessaire de vérifier que la variable existe.
Peut-être utiliser `if(!is_int($value)) return false;` plutôt ?

**Comment by P3ter** [comment]
Finalement, j'ai remplacé _is_int_ par _is_numeric_, car le test retournait _false_ pour les mois (car la clé commence par un "0").
