### ISSUE TITLE
printSelect, valeur non numérique pour selected

### ISSUE THREAD

**Issue by Philippe-M** [pluxml/PluXml#323]
dans la fonction plxUtils::printSelect pour le cas du selected, si $a est numérique avec la comparaison ne marche pas.

```
				if($a == $selected)
					echo "\t".'<option value="'.$a.'" selected="selected">'.$b.'</option>'."\n";
				else
					echo "\t".'<option value="'.$a.'">'.$b.'</option>'."\n";
			}
```

A remplacer par

```
				if(strval($a) == $selected)
					echo "\t".'<option value="'.$a.'" selected="selected">'.$b.'</option>'."\n";
				else
					echo "\t".'<option value="'.$a.'">'.$b.'</option>'."\n";
			}
```

Exemple qui marche avec la fonction actuelle :

`plxUtils::printSelect('limit', array('10'=>10, '20'=>20, '30'=>30, '40'=>40, '50'=>50), $value['limit'], '', '', '');`

Exemple qui ne marche pas avec la fonction actuel :

`plxUtils::printSelect('ordsta', array('1,2'=>'Tout', '1'=>'Non soldée', '2'=>'Soldée'), $value['ordsta'], '', '', '');`

**Comment by P3ter** [comment]
Corrigé dans la prochaine version de PluXml.
Merci @Philippe-M pour ce correctif !
