### ISSUE TITLE
Tri des tags

### ISSUE THREAD

**Issue by Loup1n** [pluxml/PluXml#327]
Message de Sudwebdesign : https://forum.pluxml.org/discussion/comment/59104/#Comment_59104

Voila, lors du choix de l'ordre des articles ds les paramètres d'affichages, cela joue aussi sur l'affichage de la page tag.php du thème graphique. Par exemple, si le mode alphabétique est choisit, les deux sont ds cet ordre.

Est-il possible qu'il y est l'option tri des articles (Mot Clé) ds les paramètres d'affichage de la prochaine mouture?

Et/ou alors comment Faire pour changer l'ordre des articles de la page tag

Cela servirai @SieurVLD en toutes probabilités et bien a d'autres

[édit] @P3ter pour allez plus loin (une idée)

Cela pourrait-être ds le moteur au préchauffage comme pour les catégories

```
public function prechauffage() {
···
    elseif($this->get AND preg_match('/^tag\/([a-z0-9-]+)/',$this->get,$capture)) {
···
    $this->tri = $this->aConf['triTag']; # Recuperation du tri des articles en mode tag
```

et le bon html ds parametres_affichage.php suffirait-il?

**Comment by lolo3129** [comment]
Bonjour, j'ai noté aussi cela sur la page admin : si on choisit article aléatoire, pour la page d'accueil, on a aussi ça par défaut sur la page admin ; pas forcément très pratique. 
PI : J'ai traité avec un plugin sur plxAdminConstruct pour redéfinir l'ordre de tri
peut être qu'on peut faire la même chose sur la page tag ?

**Comment by bazooka07** [comment]
Dans le back-office et pour le mode tags dans le front-office, les articles sont triés par date décroissante (desc)
voir PR##595
A publier dans la prochaine version de PluXml .
