### ISSUE TITLE
Gérer des templates sur la page d'erreur

### ISSUE THREAD

**Issue by Loup1n** [pluxml/PluXml#333]
Message sur le forum : https://forum.pluxml.org/discussion/6565/acces-restreint

Ajouter la possibilité d'ajouter des templates pour la page d'erreur, comme c'est le cas pour les articles et la pages statiques.

```
Dans la construction de mon site, je n'utilise pas la side-bar. je crée mes articles avec le template article-full-width.php.

Avec une mauvaise manip ( ou une manip intentionnellement mauvaise ) si j'indique une URL vers une page qui n'existe pas j'obtiens le message

"La page que vous avez demandée n'existe pas
Cet article n'existe pas ou n'existe plus !"

qui s'affiche avec la side-bar et l'accès à tous les menus
```

**Comment by bazooka07** [comment]
Dans les prochaines versions de PluXml, pour être valide, un thème devra comporter les élements suivants :
- un fichier infos.xml (critère déjà existant dans les précèdentes versions de PluXml
- un fichier de langue , définie par la constante PLX_SITE_LANG,  dans le dossier lang
- un template erreur.php
- un template pour la page d'accueil (home.php, static.php, ...)

Si un thème était supprimé par mégarde, on se rabattra sur le thème defaut livré en standard avec PluXml, et s'il n'existe plus, on recherchera un autre thème conforme aux critères précédents.

**Comment by bazooka07** [comment]
Voir PR#601
Nouvelle classe plxThemes pour gérer l'absence du thème choisi ou de la langue du site dans ce thème.
En cas de problème , on se rabat sur le thème "defaut" ou le 1er thème valide.
Si aucun thème valide, on envoie un message d'erreur en mode text/plain.
