### ISSUE TITLE
Respect de la syntaxe HereDoc

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#340]
Bonjour,
Il y a un bug dans le fichier /core/lib/class.plx.utils.php pour la fonction debugJS($obj, $msg='').
La syntaxe de HereDoc impose que le marqueur de fin _EOT_ doit démarrer en début de ligne sans espace et être seul sur cette ligne ou suivi uniquement du caractère ; (_pour le langage PHP_).
[Lire le manuel](https://www.php.net/manual/fr/language.types.string.php#language.types.string.syntax.heredoc)
 Voici le résultat d'un git diff après correction :

	@@ -1291,8 +1291,8 @@ class plxUtils {
	                        <script type="text/javascript">
	                                console.log(`$msg`);
	                        </script>
	-               
	-               EOT;
	+
	+EOT;
	        }
	 
	 }

Il y a les mêmes problèmes dans le fichier class.plx.medias.php. Utiliser **grep** pour trouver les fichiers qui utilisent la syntaxe HereDoc avec les triples chevrons :

	jpierre@smartteck:/home/www/test/PluXml$ grep -n '<<<' core/lib/*.php
	core/lib/class.plx.medias.php:169:	                return <<< OPTION
	core/lib/class.plx.medias.php:178:	    $start = <<< START
	core/lib/class.plx.medias.php:182:	    $stop = <<< STOP
	core/lib/class.plx.utils.php:1290:		echo <<< EOT
Et surveiller les logs de l'Indien 

	jpierre@smartteck:~$ tail -f /var/log/apache2/error.log

Je suppose que bien sûr vous utilisez Linux.

**Comment by P3ter** [comment]
Bonjour,
Sera corrigé avec la PR https://github.com/pluxml/PluXml/pull/338 (en cours de revue).
