### ISSUE TITLE
define vs const

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#341]
Bonjour,
Dans le fichier core/lib/config.php, on utilise encore la fonction **define()** pour définir une constante avec une chaine de texte. L'emploi de la directive **const** serait plus pertinent et plus sûr :

	const PLX_DEBUG = true;
	const PLX_VERSION = '5.8';

**Comment by bazooka07** [comment]
Il y a une autre constante qui serait intéressante d'avoir, c'est l'url du site de PluXml.
`jpierre@smartteck:/home/www/test/PluXml-2017$ grep -i 'pluxml.org' *.php core/*/*.php
install.php:		<mail><![CDATA[contact@pluxml.org]]></mail>
install.php:		<site><![CDATA[http://www.pluxml.org]]></site>
core/admin/top.php:				<li><small><a class="version" title="PluXml" href="http://www.pluxml.org">PluXml <?php echo $plxAdmin->aConf['version'] ?></a></small></li>
core/lib/class.plx.admin.php:        $url='https://www.pluxml.org/download/latest-version.txt';
core/lib/class.plx.admin.php:        $href='https://www.pluxml.org/';
core/lib/class.plx.admin.php:        $caption='PluXml.org';
`
Cette url est utilisée dans plusieurs fichiers avec les protocole http et https.
Séance de débogage en perspective si le site déménage.

**Comment by P3ter** [comment]
Done, nouvelle constante ajoutée PLX_URL_REPO dans PluXml 5.8.
