### ISSUE TITLE
plucss.css manquant dans  la branch develop

### ISSUE THREAD

**Issue by kazimentou** [pluxml/PluXml#346]
Il manque le fichier core/admin/theme/plucss.css dans la branch develop. dans la branch develop

**Comment by P3ter** [comment]
Hello, c'est normal, j'ai remplacé le `plucss.css` par sa version minifiée `plucss.min.css`, plus léger et plus rapide à charger.

**Comment by bazooka07** [comment]
Non, pas trop.
Dans l'open source le code doit être facilement lisible pour pouvoir le comprendre.
Avec un fichier minifié c'est pas trop évident.

**Comment by P3ter** [comment]
Je viens de comparer la webperf de PluXml 5.7 avec la version 5.8, mais le gain est tellement faible que je vais remettre la version non minifiée de PluCSS.

Le comparatif : https://www.dareboost.com/fr/comparison?reportIds=a_25de2c1d3a0612f50e703637f&reportIds=a_25de2c1d3a0612f50e7036380
