### ISSUE TITLE
Undefined index: password_token in PluXml-5-8\core\lib\class.plx.motor. php on line 572

### ISSUE THREAD

**Issue by jerrywham** [pluxml/PluXml#360]
Pour une archive v5.8 fraîchement téléchargée. Le premier user créé n'a pas d'index password_token dans le fichier xml correspondant...

Idem : Undefined index: password_token_expiry in PluXml-5-8\core\lib\class.plx.motor.php on line 573

**Comment by P3ter** [comment]
Corrigé sur la branche develop (PluXml 5.8.1).
