### ISSUE TITLE
Use of undefined constant PLX_TEMPLATES - assumed 'PLX_TEMPLATES' (this will throw an Error in a future version of PHP) in PluXml-5-8\core\lib\class.plx.motor.php on line 113

### ISSUE THREAD

**Issue by jerrywham** [pluxml/PluXml#361]
Et 
PHP Warning:  Use of undefined constant PLX_TEMPLATES_DATA - assumed 'PLX_TEMPLATES_DATA' (this will throw an Error in a future version of PHP) in PluXml-5-8\core\lib\class.plx.motor.php on line 114

Ce qui induit : 

PHP Warning:  scandir(PLX_TEMPLATES,PLX_TEMPLATES): Le fichier spécifié est introuvable. (code: 2) in PluXml-5-8\core\lib\class.plx.motor.php on line 1004

PHP Warning:  scandir(PLX_TEMPLATES): failed to opendir: No such file or directory in PluXml-5-8\core\lib\class.plx.motor.php on line 1004

PHP Warning:  scandir(): (errno 2): No such file or directory in PluXml-5-8\core\lib\class.plx.motor.php on line 1004

PHP Warning:  array_diff(): Expected parameter 1 to be an array, bool given in PluXml-5-8\core\lib\class.plx.motor.php on line 1004

PHP Warning:  Invalid argument supplied for foreach() in PluXml-5-8\core\lib\class.plx.motor.php on line 1005

**Comment by P3ter** [comment]
Corrigé sur la branche develop (PluXml 5.8.1)
