### ISSUE TITLE
 Uncaught Error: Class 'PlxTemplate' not found in PluXml-5-8\core\lib\class.plx.motor.php:1006

### ISSUE THREAD

**Issue by jerrywham** [pluxml/PluXml#362]
La classe n'est pas appelée dans le fichier index. Il serait peut-être bien d'utiliser un autoloader ?

**Comment by P3ter** [comment]
Corrigé sur la branche develop (PluXml 5.8.1).
Pour l'autoloader j'y suis favorable, mais dans la prochaine version de PluXml.
