### ISSUE TITLE
Détermination de la langue à utiliser pour les plugins

### ISSUE THREAD

**Issue by Loup1n** [pluxml/PluXml#368]
En parlant de langues, on pourrait en profiter pour corriger un bug qui existe sur les plugins :
si la langue choisi par l'admin n'est pas dispo sur le plugin alors on aura droit à des erreurs au lieu des chaînes de caractères. Il faudrait parcourir les langues de l'administrateur et s'il n'y a pas de correspondance créer un contournement pour afficher une des langues dispo.

_Originally posted by @ensag-dev in https://github.com/pluxml/PluXml/pull/364#issuecomment-571935480_

**Comment by bazooka07** [comment]
See PR#594
