### ISSUE TITLE
Erreur sur un nom de machine

### ISSUE THREAD

**Issue by ghost** [pluxml/PluXml#376]
J'ai installé PluXml sur une machine virtuelle et j'ai pointé dessus en utilisant le nom de la machine "test". Le souci c'est que l'installation semble bien se passer, mais après ça, je tombe sur l'erreur : **"Error: wrong or invalid url"**

En fait, PluXml vérifie l'url et provoque une erreur (core/lib/class.plx.utils.php). En effet, l'expression rationnelle qui vérifie l'url est plutôt étrange et ne sait pas gérer les "nom de machine". Il ne gère que "localhost".

**Comment by parltracker** [comment]
Ma correction temporaire : 
remplacer _([-\w]+(\.\w[-\w]*)+|localhost)_ par _([-\w]+(\.\w[-\w]*)*)_

**Comment by bazooka07** [comment]
Ta dernière parenthèse ne sert à rien. Il n'y a pas de quantificateur * ? + et on n'a a pas besoin de capturer le motif.
Mais il y a d'autres erreurs dans  l'expression initiale. Un  nom de machine doit commencer par une lettre ou un chiffre. J'ai un doute pour le cataractère _. Et il ne doit pas avoir de tiret dans l'extension. Et le caractère '.' n'est pas échappé !!!!

L'expression devrait plutôt ressembler à ceci en ajoutant les adresses IP :
^\d{1,3}(\.\d{1,3}){3}|[0-9a-z][\w-]*[0-9a-z](\.[a-z]{2,})?$

Mais je ne rencontre pas ce souci avec  la version 5.8.1 sur ma machine Smartteck :

```
sudo -u www-data php -S smartteck:8080
```

**Comment by parltracker** [comment]
Eh bien, quel accueil !

J'ai corrigé l'expression, car github avait viré les étoiles en pensant que je voulais faire de l'italique *gras*.

Pour le reste, j'ai bien précisé que l'expression avait d'autres soucis, mais je donnais un contournement possible. Maintenant, si vous ne souhaitez pas d'aide, je peux aussi rester dans mon coin ;o)

**Comment by bazooka07** [comment]
Quand tu veux insérer du code dans ton post, il faut l'encadrer avec 3 apostrophes anglaises.
Github a édité un manuel assez bien fait pour styliser son post. C'est par là :
https://guides.github.com/features/mastering-markdown/
Tu as également un onglet aperçu ( preview ) pour vérifier que l'apparence de ton post sera comme tu l'as prévu.

**Comment by P3ter** [comment]
Bonjour, je regarde ça dès que possible. Merci pour l'issue @parltracker et n'hesites pas si tu as d'autres remarques à les partager.
