### ISSUE TITLE
Création d'article invisible.

### ISSUE THREAD

**Issue by B4rb3rouss** [pluxml/PluXml#380]
- Créer un nouvel article.
- Lui donner un titre contenant un "_". Par exemple "un_super_titre".
- Publier l'article.

Il apparaît bel et bien publié dans l'interface d'administration, mais reste invisible sur la partie publique du blog.

Renommer le fichier ``/data/articles/*un_super_titre.xml`` en ``/data/articles/*un-super-titre.xml`` permet de le voir en ligne, tout en gardant le bon titre affiché. Je suppose donc que le souci vient au niveau du traitement des fichiers enregistrés dans ``/data/articles/``.

**Comment by P3ter** [comment]
Le problème vient des regex de la fonction `prechauffage()` de la class `plxAdmin`.
Je regarde et soumettrais une PR à @kazimentou qui connaît bien le sujet.
