### ISSUE TITLE
Fichiers de langues à nettoyer

### ISSUE THREAD

**Issue by P3ter** [pluxml/PluXml#388]
_Message forum : https://forum.pluxml.org/discussion/comment/60086/#Comment_60086_

* La même clé de traduction employée dans plusieurs fichiers (E.G. : L_ARTICLE, L_CATEGORY, L_NO_ARTICLE employés dans core.php et admin.php )
* Plusieurs clés pour une même traduction (E.G. : L_PLUGINS_ACTION, L_COMMENTS_LIST_ACTION, L_CONFIG_USERS_ACTION, L_STATICS_ACTION, L_ARTICLE_LIST_ACTION pour "Action" )

**Comment by bazooka07** [comment]
J'ai commencé à faire les modifs des fichiers linguistiques avec grep sed.
Je fais un "git commit" à chaque modif de clés
branch langs-2003 sur https://github.com/kazimentou/PluXml.git
J'ai déjà fait 2 clés à la main pour tester. Il me faut maintenant un script shell pour automatiser.
J'enverrai un PR à la fin
J'espère bien remplacer les tablaux $LANGS par des constantes en pur et dur
A la fin de la semaine, le problème devrait être réglé

**Comment by kazimentou** [comment]
Voir PR : https://github.com/pluxml/PluXml/pull/389

**Comment by P3ter** [comment]
Merci beaucoup pour tout ce travail.
Je suis passé rapidement sur les commits ça m'a l'air tout bon. Je vais faire quelques tests avant de merger sur master et de mettre un message sur le forum.

**Comment by P3ter** [comment]
Done.
