### ISSUE TITLE
Editor for comments is empty

### ISSUE THREAD

**Issue by P3ter** [pluxml/PluXml#418]
PluXml administration, the editor for a comment is empty, when there is at least one answer to this comment. The editor for this answer is empty too.

The editor for a comment which don't have any answer is OK.

![image](https://user-images.githubusercontent.com/1431205/79690656-c8c1cb80-825b-11ea-8063-17f8affc5bd2.png)

**Comment by antistress** [comment]
Also note that, despite the comment can't be modified since the editor is empty as pointed above, I however can answer that buggy comment via the editor which then manage to quote the buggy comment.

**Comment by dadall** [comment]
I don't if it is related but I have a "ghost" comment I don't know how to get rid of
![Screenshot_2020-04-23 Blog de dada Administration](https://user-images.githubusercontent.com/2796341/80068595-28f88c00-8540-11ea-9633-304d9087baa6.png)

**Comment by P3ter** [comment]
Yes I think it's the same problem. I try to edit a waiting comment on PluXml 5.8.3 and it works now.
