### ISSUE TITLE
Missing delimiters in preg_grep in plxAdmin editCategories()

### ISSUE THREAD

**Issue by sudwebdesign** [pluxml/PluXml#462]
https://github.com/pluxml/PluXml/blob/436ad00e681d089131ee58e326c1a9094a6b60b1/core/lib/class.plx.admin.php#L659

missing modified **[0-9]{3}** TO **#\d{3}#**
Will be good with this replacement :
```PHP
	if(count(preg_grep('#\d{3}#', $filenameArrayCat)) > 1) {
```

**Comment by bazooka07** [comment]
You are missing some tricks :
```
grep -n '\[0-9\]' *.php update/*.php core/{admin,lib}/*.php
echo "$(grep -n '\[0-9\]' *.php update/*.php core/{admin,lib}/*.php | wc -l) lines"
```
Just 34 lines for checking.
You can use "sed" for a batch of replacements

**Comment by sudwebdesign** [comment]
Marvelous tricks :+1: 
Found this Notice with debug = true in config ;)
