### ISSUE TITLE
Fix tag Tag is never active in "tag" mode : url ?tag/Tag

### ISSUE THREAD

**Issue by sudwebdesign** [pluxml/PluXml#466]
* Fix Notice in plxShow->artTags() : $t is undefined : motor mode tag
https://github.com/pluxml/PluXml/blob/436ad00e681d089131ee58e326c1a9094a6b60b1/core/lib/class.plx.show.php#L784
Fixed with this var typo (cible==$t To cible==$tag) : 
```
	'#tag_status'	=> ($this->plxMotor->mode=='tags' AND $this->plxMotor->cible==$tag) ? 'active' : 'noactive'
```

**Comment by bazooka07** [comment]
Non, $this->plxMotor->cible stocke la valeur du résultat de plxUtils::urily() voir ligne 214 dans plxMotor::prechauffage() dans PluXml 5.8.9
