### ISSUE TITLE
Fix admin statiques default _menu param '1' to 'oui'

### ISSUE THREAD

**Issue by sudwebdesign** [pluxml/PluXml#469]
https://github.com/pluxml/PluXml/blob/436ad00e681d089131ee58e326c1a9094a6b60b1/core/admin/statiques.php#L136
c'est 'oui' ou 'non' le choix du param :)
```
	plxUtils::printSelect($new_staticid.'_menu', array('oui'=>L_DISPLAY,'non'=>L_HIDE), 'oui');
````

**Comment by kazimentou** [comment]
Don't say 'oui' or 'non'. It's just good for french people.
Just say '1' or '0' and that' right for every language.

**Comment by bazooka07** [comment]
PR #474
https://github.com/pluxml/PluXml/pull/474

**Comment by P3ter** [comment]
Merged on master, thanks to you two.
