### ISSUE TITLE
Return au lieu d'echo dans $plxshow->catName

### ISSUE THREAD

**Issue by Philippe-M** [pluxml/PluXml#478]
Bonjour,

Dans la fonction $plxShow->catName remplacer :
```
			if($type == 'link')
				echo '<a href="'.$url.'" title="'.$name.'">'.$name.'</a>';
			else
				echo $name;
```

par
```
			if($type == 'link')
				echo '<a href="'.$url.'" title="'.$name.'">'.$name.'</a>';
			elseif($type == 'get')
				return $name;
			else
				echo $name;
```
Permet de choisir au niveau du thème si on affiche le texte brut ou alors le lien avec le balisage html

**Comment by bazooka07** [comment]
PR#596

J'ai ré-écrit la fonction plxShow::catName($type).
Si $type=='link' on affiche un lien pointant vers la catégorie
Si empty(trim($type)) on affiche le nom de la catégorie
Sinon on retourne (return) le nom de la catégorie

"Merged" pour la prochaine version de PluXml.
