### ISSUE TITLE
On déménage les fichiers CSS

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#480]
Pour la branche master :

Les fichiers CSS ont été déplacés dans le dossier core/admin/theme/css.
la correction des "link" a bien été faite dans le fichier core/admin/top.php côté back-office
Par contre pour une installation toute neuve, les "link" ne sont plus à jour dans install.php

voir PR #481 

_P.S._ : Cela serait bien de changer la valeur de PLX_VERSION dans la branche master. Actuellement 5.8.3. 
5.9.0 ou 6.0.0-rc seront plus pertinents et permettront de tester les plugins pour la future version de PluXml.

**Comment by P3ter** [comment]
Oui, je vais faire le changement.
Merci pour la PR elle a été mergée.
