### ISSUE TITLE
Improvement: Making PluXml more accessible to the world

### ISSUE THREAD

**Issue by ghost** [pluxml/PluXml#488]
Good morning,

i find your cms over david revoys website. It looks interesting and promising, but for a non-french audience its very hard to install either to contribute. I look around on pluxml.org and it seems you have a lot of languages for the ui in the software, but the website and the documentation is not translated (or i dont find how i switch the language of the website/documentation, at the moment, i translate everything via chrome).

It would be nice if you could make pluxml.org more accessible to the world with a translated website and documentation. 

Best Regards

milame

**Comment by P3ter** [comment]
Hi,

Yes you're right and the translation of the website and the documentation are planned. PluXml.org will be available in French and English, as soon as possible.

Regards.
