### ISSUE TITLE
Impossible de sauvegarder le contenu d'un article Pluxml 5.8.4

### ISSUE THREAD

**Issue by ktux** [pluxml/PluXml#506]
Bonjour,

Lors de la création d'un nouvel article, tout le contenu que j'essaye d'enregistrer en tant que brouillon ou de publier s'efface. Voici ce que j'ai trouvé dans les logs d'Apache et qui semble être à l'origine du problème. 

[php7:notice] [pid 26693] [client 86.10.0.1:0] PHP Notice:  Undefined index: tags in /var/www/html/pluxml/core/lib/class.plx.motor.php on line 696

Je n'avais jamais rencontré ce problème avant la mise à jour vers la version 5.8.4. Bizarrement, le contenu du chapô lui est bien sauvegardé. Pourriez-vous m'aider à résoudre ce problème car je ne peux plus publier d'article pour l'instant.

Le serveur fonctionne sous Debian 10.6 avec la version Apache 2.4.38 et php 7.3.19 derrière un reverse-proxy sous Nginx.

Merci.

**Comment by P3ter** [comment]
Bonjour,

Le log semble indiquer que l'attribut "tags" serait absent de l'article. Pourrais-tu vérifier dans data/articles si dans le fichier XML correspondant à l'article, l'attribut "tags" est absent, stp ? Je vais continuer de regarder comment on pourrait arriver dans ce cas de figure.

**Comment by dadall** [comment]
Coucou,

Je rentre le même souci mais avec la branch 6 avec laquelle je m'amuse : les articles sont bien sur le serveurs, avec draft dans le nom mais ils n'apparaissent pas l'interface d'admin.

Je confirme que <tags> est bien là.

**Comment by P3ter** [comment]
Oui je confirme, je viens de reproduire le bug en publiant l'article pour la sortie de PluXml 5.8.5 (oui c'est ballot...). Pour mon cas, j'ai l'impression que le problème vient de la présence de . (point) dans le titre de l'article. En saisissant le champ "url" à la main, sans mettre les points ça fonctionne. Je vais creuser pour avoir une correction dans une version 5.8.6.

**Comment by P3ter** [comment]
Au temps pour moi, c'est corrigé dans la version 5.8.5, via la pull request https://github.com/pluxml/PluXml/pull/505
