### ISSUE TITLE
Chapo toujours présent

### ISSUE THREAD

**Issue by dadall** [pluxml/PluXml#515]
Bonjour,

En version 6, et 5.8 aussi, il n'est plus possible de faire un article sans chapo : on a toujours un < br /> qui traine.

**Comment by P3ter** [comment]
Bonjour,

Je n'ai pas réussi à reproduire le bug, à moins d'avoir mal compris. J'ai créé un article sans renseigné le chapo, et que se soit suite à l'enregistrement (brouillon) ou suite à la publication, je n'ai pas trouvé de "<br>" qui traine. 

Le contenu de l'article : 

```
<?xml version='1.0' encoding='UTF-8'?>
<document>
	<title><![CDATA[Nouvel article #515]]></title>
	<allow_com>1</allow_com>
	<template><![CDATA[article.php]]></template>
	<chapo><![CDATA[]]></chapo>
	<content><![CDATA[le chapo contient-il un <br> ?]]></content>
	<tags><![CDATA[]]></tags>
	<meta_description><![CDATA[]]></meta_description>
	<meta_keywords><![CDATA[]]></meta_keywords>
	<title_htmltag><![CDATA[]]></title_htmltag>
	<thumbnail><![CDATA[]]></thumbnail>
	<thumbnail_alt><![CDATA[]]></thumbnail_alt>
	<thumbnail_title><![CDATA[]]></thumbnail_title>
	<date_creation><![CDATA[202101031915]]></date_creation>
	<date_update><![CDATA[202101031917]]></date_update>
</document>`
```

L'attribut `chapo` est bien vide.

**Comment by dadall** [comment]
En créant un article : 

```
<?xml version="1.0" encoding="UTF-8" ?>
<document>
		<title><![CDATA[toto42]]></title>
		<allow_com>1</allow_com>
		<template>article.php</template>
		<chapo><![CDATA[<br />]]></chapo>
		<content><![CDATA[testse]]></content>
		<tags></tags>
		<meta_description></meta_description>
		<meta_keywords></meta_keywords>
		<title_htmltag></title_htmltag>
		<thumbnail></thumbnail>
		<thumbnail_alt></thumbnail_alt>
		<thumbnail_title></thumbnail_title>
		<date_creation>202101032003</date_creation>
		<date_update>202101032003</date_update>
</document>
```

J'ai beau virer de **br**, il revient toujours :'(

**Comment by P3ter** [comment]
Est-ce que tu utilises un plugin pour éditer tes articles et si oui lequel (plxEditor, CkEditor, ...) ?

**Comment by dadall** [comment]
En image : 

![Screenshot_2021-01-03 Blog de dada Administration](https://user-images.githubusercontent.com/2796341/103486675-c27e7a00-4dff-11eb-87fc-b8f68abfea41.png)

**Comment by dadall** [comment]
> Est-ce que tu utilises un plugin pour éditer tes articles et si oui lequel (plxEditor, CkEditor, ...) ?

Voui : plxeditor !

**Comment by dadall** [comment]
J'avais une vielle version de plxEditor. J'ai mis à jour le plugin via https://ressources.pluxml.org/plugins/PlxEditor

Toujours le même souci.

Par contre, en passant par CkEditor : aucun problème, si ce n'est que j'aime pas ce plugin :o)

**Comment by bazooka07** [comment]
Le bug vient du plugin et non de PluXml.
Tu peux remédier au problème en modifiant la fonction "create.prototype.updateTextArea" dans le fichier plugins/plxEditor/plxEditor/plxEditor.js (voir dernière ligne de code) :
```javascript
	create.prototype.updateTextArea=function() {
		if(this.viewSource) { this.toggleSource(); }
		txt = this.frame.document.body.innerHTML;
		txt = this.convertLinks(txt, 1); // conversion des liens
		txt = this.toXHTML(txt);
		E$(this.textareaId).value = txt.replace(/<br\s*\/>$/, '');
	},
```

**Comment by dadall** [comment]
Merci !

**Comment by P3ter** [comment]
J'ai mis à jour le plugin en 1.7, avec une légère modification de la regex pour prendre en compte Firefox, qui ajoute un `<br>` à la différence de Chrome qui lui ajoute un `<br />`.

https://ressources.pluxml.org/plugins/PlxEditor

**Comment by bazooka07** [comment]
Bonjour,

Dans l'expression "E$(this.textareaId).value = 
txt.replace(/<br\s*?\/?>$/, '');", le modificateur "?" est inutile après 
"\s*".

L'expression suivante est suffisante :

E$(this.textareaId).value = txt.replace(/<br\s*\/?>$/, '');

Le 08/01/2021 à 10:05, P3ter a écrit :
