### ISSUE TITLE
.htaccess n'est pas accessible en écriture ou n'existe pas

### ISSUE THREAD

**Issue by dadall** [pluxml/PluXml#517]
Coucou,

Je sens que c'est une erreur bête mais je n'arrive absolument pas à virer ce message quand j'essaie de modifier les configurations avancées.
Une idée ?

- Les droits sont bons
- Je me sers de Nginx
- Je suis sous Debian
- Ajouter un htaccess à la main ne change rien

**Comment by bazooka07** [comment]
Hi,
Les fichiers .htaccess ne servent à rien quand PluXml est hébergé sur un serveur Nginx !
Tu trouveras comment configurer le virtual host de Nginx pour gérer les redirections ici :
https://wiki.pluxml.org/installer/nginx/
Perso, j'utilise PluXml avec Nginx sur une carte SBC (_small board computer_) [BananaPi Berry](http://wiki.banana-pi.org/Banana_Pi_BPI-M2_Berry)
l'OS est Armbian une version spéciale de Debian pour processeur Arm.

**Comment by dadall** [comment]
Bah ! C'est tout à fait vrai et j'avais une (très vielle) coquille dans ma conf nginx...

Merci !
