### ISSUE TITLE
& remplacé par &amp; dans urlrewrite

### ISSUE THREAD

**Issue by Philippe-M** [pluxml/PluXml#519]
Dans le cas où la ré-écriture d'url est active les `&` sont remplacées par l'équivalent html  `&amp;`

https://github.com/pluxml/PluXml/blob/d7f3845a10f453d316677f96441ce5b9956320b7/core/lib/class.plx.motor.php#L1103

Alors que le `&` est utilisé comme séparateur de paramètres passées en GET

**Comment by P3ter** [comment]
Hello,
Avec la réécriture de cette fonction dans PluXml 5.8.6 (https://github.com/pluxml/PluXml/pull/520), ce bug devrait maintenant être corirgé.
