### ISSUE TITLE
Admin : doublon id="mnu_parametres_base.php"

### ISSUE THREAD

**Issue by RolandTi** [pluxml/PluXml#527]
Hello,
dans la génération des ids du menu admin, si j'ai bien compris, l'id est celui du fichier, c'est décrit dans `public static function formatMenu`. Du coup lorsqu'on est sur la page `parametres_base.php`, on se retrouve avec 2 fois le même ID, sur Paramètres et sur Configuration de base. 

C'est pas grand chose et ça semble un peu compliqué à corriger (trop pour moi). Donc n'en tenez pas forcément compte :)

**Comment by bazooka07** [comment]
Bonne remarque. 
Mais j'avais déjà repéré ce problème et apporté une correction pour la prochaine version 6.0.0 de PluXml
Ma solution est de supprimer l'entrée "paramètres" quand on affiche une page d'un fichier dont le nom commence par "parametres_".
Sinon on a 2 entrées dans le menu qui pointent vers la page "parametres_base.php".
Autre remarque : avoir ".php" dans l'id n'a aucun intérêt sémantique. Que je supprime dans ma solution.
Autre remarque : Pour les non--initiés, rien n'indique que "paramètres" permet d'ouvrir un sous-menu. Cela est génant pour les nouveaux venus  PluXml.
Ces 2 derniers points sont pris en compte dans ma solution.

**Comment by RolandTi** [comment]
Nickel, du coup c’est corrigé pour la v6 ? Alors je ferme, merci !
