### ISSUE TITLE
content static 1 missing and saving fails

### ISSUE THREAD

**Issue by patch-works-be** [pluxml/PluXml#538]
Hello,
I installed PluXML 6.0 on Infomaniak PHP 7.3 with basic dataset.
I'm testing a personal theme developed for PluXML 5.8.6  where <?php $plxShow->staticInclude(1); ?> is added in the footer template
But no content is shown; static 1 is indeed empty, and adding content fails: when saving, the new text disappears

**Comment by kazimentou** [comment]
See :
- https://github.com/pluxml/PluXml/pull/575 
- https://forum.pluxml.org/discussion/7265/static-et-articles-en-page-daccueil
