### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by zidingz** [pluxml/PluXml#543]
Hey there!

I belong to an open source security research community, and a member (@noobpk) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by P3ter** [comment]
Hi, thanks for this suggestion. I added the file to `.github` : https://github.com/pluxml/PluXml/security/policy

**Comment by noobpk** [comment]
@P3ter HI, You can access [https://huntr.dev/bounties/7600557b-204c-4388-8989-e64f7230167f/](https://huntr.dev/bounties/7600557b-204c-4388-8989-e64f7230167f/) to review and validate my report. 
Thanks ^^!!
