### ISSUE TITLE
Use of Hard-coded Cryptographic Key

### ISSUE THREAD

**Issue by Loup1n** [pluxml/PluXml#548]
Key encryptID/decryptID Hardcoded in Source Code.

Storing encryption keys in plain text anywhere on the system allows anyone with sufficient permissions to read and potentially misuse the encryption key.

Path: ../core/lib/class.plx.encrypt.php

https://huntr.dev/bounties/07099a3a-872f-4796-960d-cf76e5ee0164/?token=57d6fb2a1d8932d2cc008c88d5f865f88553ecf12b0dfceb5b0a3b29ca6735f35a07f2e532e1a861fd728c113c5077e06bf01d204a2da61d14d6e099f26222bf63947d9c6f493ff2679517e79342ccb5b78c1c8984ab3321080dbf0397ea36a82ce52dbe5ff944351f3f626c4cf322e577acecef23e6f880a2

**Comment by bazooka07** [comment]
See PR #653 for the next version of PluXml.
Encryption key is computed from the datetimes of three files.
And openssl_encrypt() is used for encryption.
Enjoy !
