### ISSUE TITLE
PluXML 5.8.9 : Les commentaires postés n'apparaissent pas dans l'espace admin en mode modération

### ISSUE THREAD

**Issue by broncowdd** [pluxml/PluXml#574]
* Maj depuis une version ancienne de pluXML (5.8.2)
* PHP 7.4.3 en local / 7.4 sur mon hébergeur
* mode modération des commentaires on
* bug rencontré sur une version 5.8.2 mise à jour mais également sur une version 5.8.9 native venant d'être installée (en local)
* semble indépendant des plugins installés
* indépendant du navigateur (firefox/opéra/vivaldi testés)

Quand la modération est à ON, les commentaires postés n'apparaissent pas dans l'espace admin>commentaires (ni publiés, ni en attente)
Pourtant le fichier XML de commentaire est bien créé.

**Comment by broncowdd** [comment]
Complément d'information: si on met un commentaire offline depuis la page admin>comment, celui-ci disparaît et le nb de commentaires offline n'augmente pas (de plus le commentaire en question n'apparaît pas dans la rubrique offline de comment.)

**Comment by broncowdd** [comment]
Autre bug trouvé (sur un pluXml 5.8.9 vierge et sans plugins):
Si je crée un nouvel article et que je lui donne le titre «Film: Les Folies Fermières », l'URL conservée lors de la création est identique (comme si la normalisation de l'URL ne se faisait pas)  ce qui génère un bug au moment de l'affichage de l'article (home.php ou article.php) : l'article n'apparaît tout simplement pas.
Si je change l'URL, ça fonctionne.

**Comment by kazimentou** [comment]
Voir PR #571 pour les commentaires à valider
https://github.com/pluxml/PluXml/pull/571

**Comment by kazimentou** [comment]
Avec un titre comme indiqué, la fonction PHP parse_url() employée par plxUtils::urlify() considère que "Film:" est un protocole comme "http:" ou "https:".
Il faut modifier le début de la fonction plxUtils::urlify() comme ceci :
`
public static function urlify($url, $remove=false, $replace='-', $lower=true) {
 
               if (preg_match('#^(?:https?|s?ftp)://#', $url)) {
                       # adresse url absolue
                       return $url;
                }
`
