### ISSUE TITLE
index.php => install.php et lib/config.php

### ISSUE THREAD

**Issue by gcyrillus** [pluxml/PluXml#620]
Bonjour,

Sur une installation depuis zero de la version 5.8.10 en date, Une mise en orbite du script via 
```
# On verifie que PluXml est installé
if(!file_exists(path('XMLFILE_PARAMETERS'))) {
	header('Location: ' . PLX_ROOT . 'install.php');
	exit;
}

```
dans lib/config.php  _lib/config.php est inclus à index.php et install.php_ 

empeche l'affichage de install.php .

Il vaudrait mieux pour install.php de faire le test inverse: afficher si pas installer :) ... si le proprio du site n'a pas effacer ce fichier.

Bonnes fêtes

**Comment by bazooka07** [comment]
Effectivement, cela va tourner en boucle. 
On rajoute un test sur $_SERVER['SCRIPT_NAME'] :

```
if(!file_exists(path('XMLFILE_PARAMETERS')) and basename($_SERVER['SCRIPT_NAME']) != 'install.php') {
	header('Location: ' . PLX_ROOT . 'install.php');
	exit;
}
```
https://github.com/pluxml/PluXml/pull/624/files#diff-f7cae1669200b9c0c3d1ab283ec8d7c5567e6e2cd68b1770a60bd6569cbb2f86
