### ISSUE TITLE
Creation of dynamic property plxMotor::$cibleName is deprecated

### ISSUE THREAD

**Issue by Txori** [pluxml/PluXml#666]
Je suis récemment passé à PHP 8.2.8 et depuis j'ai ce warning qui tombe assez souvent dans le nginx log:

`Got error 'PHP message: PHP Deprecated: Creation of dynamic property plxMotor::$cibleName is deprecated in /core/lib/class.plx.motor.php on line 225'.`

Les variables doivent être initialisées, du coup, il suffirait d'ajouter `private $cibleName;` dans la class plxMotor,
ou ajouter `#[AllowDynamicProperties]`

Explications : https://php.watch/versions/8.2/dynamic-properties-deprecated

Bonne journée :)

**Comment by haruka-repo** [comment]
Thanks! Fixed in PluXml 5.8.10.
