### ISSUE TITLE
warning dans core/lib/config.php ligne 168 si test class_exists('plxXx')/class_exists('PlxXx') 

### ISSUE THREAD

**Issue by gcyrillus** [pluxml/PluXml#667]
En testant la disponibilité d'une class (ex: un plugin) si ce plugin à un nom commençant avec les lettres
**Plx** ou **plx** suivi d'un majuscule **PlxM** / **plxM** et d'une ou plusieurs lettres (indifféremment en majuscule ou minuscule) 

par exemple si l'on teste la présence du plugin de stéphane PlxMySearch et que ce plugin n'est pas actif, on a droit à:
>Warning: include_once(....\PluXml-5.8.10\core\lib/class.plx.mysearch.php): failed to open stream: No such file or directory in ....\PluXml-5.8.10\core\lib\config.php on line 168

Ou si l'on teste un plugin du nom de plxXx ou PlxXx  `<?php  if (class_exists('PlxXx')) {echo 'Yop';} ?>`

 >Warning: include_once(.....\PluXml-5.8.10\core\lib/class.plx.xx.php): failed to open stream: No such file or directory in ....\PluXml-5.8.10\core\lib\config.php on line 168

On peut taire les warnings avec @  `<?php  if (@class_exists('PlxXx')) {echo 'Yop';} ?>`

cdt

**Comment by bazooka07** [comment]
Voir PR https://github.com/pluxml/PluXml/pull/705

Testé  avec le contenu suivant d'une page statique :
```
<p>Test du plugin plxMySearch</p>
<hr />
<p><?= (class_exists('PlxMySearch')) ? 'actif' : 'inactif' ?></p>
<hr />
```

__Note :__
le chargement automatique ne se fait que pour les class de PluXml.
Les class des plugins doivent être explicitement chargées.

**Comment by gcyrillus** [comment]
Oups, j’avais oublié de précisé que c’était un test depuis un plugin interrogeant la présence d'un autre plugin. 

code minimal qui donne un warning jusqu’à la version 5.9.0-rc2 incluse:

```
public function ThemeEndHead() {			
			echo self::BEGIN_CODE;
		?>
		# teste présence plxMysearch 
		if(class_exists('plxMySearch')) {  
				// action à effectuer
		}
		<?php			
            echo self::END_CODE;			
		}
```

Ce défaut n'existe plus dans la 5.9.0-rc3  :)
