### ISSUE TITLE
impossibilité de decoché une statique mise précedement en Acceuil

### ISSUE THREAD

**Issue by gcyrillus** [pluxml/PluXml#669]
Cette portion de code dans class.plx.Admin.php en l'état, peut-être retirée 

```
			 elseif($k == 'homestatic') {
				if(
					empty(trim($v)) or
					!preg_match('#^\d{3,4}$#', $v)
				) {
					continue;
				}

			}
```
**fait double emploi** et empeche le ***vidage*** du champ `homestatic` dans le fichier de configuration de PluXml.

**Comment by kazimentou** [comment]
Non, cela ne fait pas double emploi.  On filtre cette valeur pour le formulaire posté par un humain.
Par contre le test est effectivement erronné.
Voici la correction :
```
			elseif($k == 'homestatic') {
				if(
					!empty($v) and
					!array_key_exists($v, $this->aStats)
				) {
					continue;
				}

			}
```

Je vais publier un commit très prochainement.

**Comment by gcyrillus** [comment]
superbe, merci

**Comment by bazooka07** [comment]
Voir commit :
https://github.com/pluxml/PluXml/commit/7002c16a587141882ce20fe2c2de563ed04b854f

Je m'interroge sur la pertinence d'afficher la page static qui sert de homepage dans le menu généré par plxShow::staticList(). Certes on peut agir dans le panneau de config pour désactiver cet affichage mais pour un newbie ce n'est pas forcément instinctif.
Ton avis ?

**Comment by haruka-repo** [comment]
Je ne pense pas que ça pose problème, ça me semble assez simple, même pour un newbie, d'aller mettre la page en "masquer" depuis l'admin et ça éviterait de gérer un cas particulier dans le code. Je préfère garder la mécanique existante.

**Comment by gcyrillus** [comment]
Il y aussi Cpalo qui souhaiter retirer le lien vers la page d'accueil lorsque l'on etait sur la page d'acceuil ;) 
Je lui avais proposé ceci qui semble convenir:
```
<?php $homeLink = ($plxShow->mode() =='static'  && $_SERVER['QUERY_STRING'] =='' ) ? '' :  $plxShow->getLang('HOME') ;  ?>
    <?php $plxShow->staticList($homeLink,'<li class="#static_class #static_status" id="#static_id"><a href="#static_url" title="#static_name">#static_name</a></li>'); ?>
```
cdt

**Comment by haruka-repo** [comment]
Pour ce cas on pourrait ajouter un nouveau paramètre booléen à plxShow::staticList(), quelque chose du genre : 

`<?php $plxShow->staticList('$extra', '$format', '$format_group', $display_home) ?>`

**Comment by bazooka07** [comment]
La remarque de @cpalo rejoint ce que j'ai proposé. Pour satisfaire tout le monde, on peut passer une option à plxShow::staticList($extra, $format, $format_group, $menublog).
Par contre, cela m'ennuie d'ajouter une nouvelle option après $menublog car il faut renseigner en même temps les valeurs de $format et $format_group.
Une alternative est de tester le type de $extra. Si type string pas de changement. si type boolean avec valeur false, on n'affiche pas le lien.
Il y a le même souci quand on donne une valeur numérique à $menublog. Il faut aussi renseigner avec des strings $format et $format_group. Une alternative serait de passer des valeurs boolénnes à la place pour prendre les formats par défaut.
En jetant un oeil dans le code de PluXml, je constate que le test sur $menublog est incorrect. On teste s'il est vrai au lieu de tester une valeur numérique positive.
J'attends vos retours pour tester cela.

Il y a la remarque sur le titre de page de Txori posté ce jour sur le forum.

**Comment by cpalo** [comment]
Bonsoir,
j'ai utilisé ce que gcyrillus m'avait proposé. Et ça fonctionne impeccable.

**Comment by haruka-repo** [comment]
@bazooka07 
> Par contre, cela m'ennuie d'ajouter une nouvelle option après $menublog car il faut renseigner en même temps les valeurs de $format et $format_group.

Est-ce qu'on ne devrait pas laisser à `null` les valeurs des paramètres et tester avec empty() dans la fonction pour appliquer les valeurs par défaut, pour éviter ça ? Car même si on est pas `strict_types=1` sur plxShow, je préfère ça que de passer des paramètres qui peuvent avoir plusieurs types (`string` ou `bool`) et que l'on test le type dans la fonction. C'est d'ailleurs à cause de ça qu'il y a effectivement un bug sur le paramètre `$menublog`.

> Il y a la remarque sur le titre de page de Txori posté ce jour sur le forum.

Je n'ai pas encore regardé les impacts de ça, mais sur le principe je pense qu'on peut faire de sorte de ne plus rendre le titre obligatoire sur les pages

**Comment by bazooka07** [comment]
Effectivement on peut passer null en paramètres et tester avec is_null pour prendre les formats par défaut.
