### ISSUE TITLE
Une typo dans le fichier footer.php du thème par défaut

### ISSUE THREAD

**Issue by gcyrillus** [pluxml/PluXml#670]
Une balise image n'est pas refermée.

**themes>defaut>footer.php**
ligne 16 `<a href="#top" title="<?php $plxShow->lang('GOTO_TOP') ?>"><img src="<?php $plxShow->template(); ?>/img/up.svg" alt="▲"</a>` .
correction :  `<a href="#top" title="<?php $plxShow->lang('GOTO_TOP') ?>"><img src="<?php $plxShow->template(); ?>/img/up.svg" alt="▲"></a>`

**Comment by haruka-repo** [comment]
Merci ! C'est corrigé sur la version 5.8.10.

**Comment by gcyrillus** [comment]
Merci :)

**Comment by gcyrillus** [comment]
Oups, Le fichier up.svg semble manquant dans le dossier **img** du thème.
cdt

**Comment by haruka-repo** [comment]
C'est corrigé sur le branche 5.9, merci.
