### ISSUE TITLE
Mauvaise gestion des branches sur github

### ISSUE THREAD

**Issue by bazooka07** [pluxml/PluXml#677]
La prochaine version de PluXml qui sera publiée sera la version 5.9.0.
Elle devrait être sur la branche de travail par défaut soit : master
La version 6.0 dont la publication est très lointaine doit être sur une branche 6.0 ou autre. Cette dernière sera mergée sur la branche master quand la version officielle 5.9.0 sera publiée.
A l'état actuel, il est compliqué d'envoyer des correctifs pour la version 5.9.0 par des pull requests

**Comment by haruka-repo** [comment]
Yes je m'en occupe.
