### ISSUE TITLE
Mise à jour automatique

### ISSUE THREAD

**Issue by jvoisin** [pluxml/PluXml#71]
Ce serait chouette d'avoir un système de mise à jour automatique.
 - [ ] Une option pour autoriser pluxml à aller vérifier s'il y a une version plus récent de disponible.
 - [ ] Un moyen de faire télécharger et décompresser la nouvelle version.

**Comment by pluxml** [comment]
la vérification d'une nouvelle version est déjà implémentée
le téléchargement et la décompression automatique suggère des contrôles de sécurité supplémentaires ce qui rend difficile son implémentation sans alourdir PluXml. Suggestion non retenue donc.
