### ISSUE TITLE
 "pivoter à gauche" ou "pivoter à droite" pour les images

### ISSUE THREAD

**Issue by cfdev** [pluxml/PluXml#81]
Ajouter une fonction "pivoter à gauche" ou "pivoter à droite" pour les images, si possible...

Etude de faisabilité

Merci

**Comment by jerrywham** [comment]
Il existe un plugin pour ça qui permet de renommer les images également : http://www.ecyseo.net/data/documents/telechargements/plugins/imagemanager.zip

**Comment by cfdev** [comment]
... en effet merci jerry je pense que le plugin de jéjé pour centraliser les dépots va grandement facilité la recherche :+1: :smile:
