### ISSUE TITLE
Changement de langue à l'installation : 5.9.0-rc7

### ISSUE THREAD

**Issue by Benjamin-Voyons** [pluxml/PluXml#824]
J'ai installé Pluxml version 5.9.0-rc7, en local, et le changement de langue ne se fait pas à la volée, bien qu'il soit pris en compte lors de l'installation.

**Comment by bazooka07** [comment]
Le changement de langue à l'installation n'est pas prise en compte si on choisit "en"
Corrigé avec le commit  suivant :
https://github.com/pluxml/PluXml/pull/831
