### ISSUE TITLE
Autorisation des commentaires : 5.9.0-rc7

### ISSUE THREAD

**Issue by Benjamin-Voyons** [pluxml/PluXml#825]
Testé en local, sauf erreur de ma part il y a un problème avec l'autorisation des commentaires :

Article rédigé avec l'option _abonnés seulement_ dans celui-ci, l'article est sauvegardé avec le paramètre : "allow_com" =  "0" :

- Lorsque les commentaires ont l'option _**abonnés seulement**_ dans les paramètres de base
- Lorsque les commentaires ont l'option _**Tout le monde**_ dans les paramètres de base
- Il est possible pour quiconque de rédiger un commentaire

**Comment by bazooka07** [comment]
Voir commit https://github.com/pluxml/PluXml/pull/848
Le thème defaut a été repris pour les commentaires  réservés aux abonnés/utilisateurs ( _authentification via auth.php_ )
