### ISSUE TITLE
How to change language of the documentation?

### ISSUE THREAD

**Issue by ardesan** [pluxml/PluXml#826]
Hi PluXML Team,

the description of your project said "Translated into 11 languages  [...]", but at least the default language of the documentation is french. Is it possible to change language of the documentation, because i do not find a option for that and dont speak french.

Thanks in advance

**Comment by bazooka07** [comment]
Hello,You can use Google to translate french documentation into english or other language :
 https://translate.google.com/?sl=fr&tl=en&text=https%3A%2F%2Fwiki.pluxml.org%2F&op=translate
You can post any question in english here :
https://forum.pluxml.org/
Translating documentation in english take a long time and we are a few volunteers.

**Comment by ardesan** [comment]
I see, thanks ! 👍
