### ISSUE TITLE
Ajout d'un template engine

### ISSUE THREAD

**Issue by mistergraphx** [pluxml/PluXml#83]
Bonjour,

Je ne sais pas si ça a déjà été évoqué, je n'ai pas vraiment trouvé de discussion passées sur le sujet...

J'utilise depuis quelques années pluxml sur quelques sites et je trouverais vraiment plus agréable pour la rédaction de themes ou templates d'intégrer un template engine a PluXML. Les avantages autres étant de bénéficier d'un système de cache, sécurisé certaines actions naturellement , une syntaxe plus propre que les eval et <? ;-) ...

J'ai pas mal utilisé mustache, qui est léger et performant, et disponible sous pas mal de langages, ce qui permet une portabilité des templates. Dernièrement j'ai plus opté pour liquid ou twig/swig, qui me parait une syntaxe + flexible et agréable, ainsi qu'une disponibilité portabilité sous pas mal de langages.

y'aurais il des avis ? des suggestions quand à la manière de l'intégrer ?

**Comment by juanito003** [comment]
Pico CMS est sympa, mais ne permet pas de gérer des commentaires.
Concernant le moteur de template pour pluXml, j'aimerais beaucoup qu'il utilise Twig.

Je ne vois pas en quoi cela pourrait être un frein. La documentation de Twig est très simple et cela se prend en main en une après-midi. La courbe d'apprentissage est petite pour un résultat de taille.
Il faudrait proposer un sondage aux gens qui font des templates pour voir comment ils accueilleraient Twig.

**Comment by mistergraphx** [comment]
j'ai codé mon propre outil après avoir utilisé Pico, quelques temps, et l'avoir modifié a foison pour mon propre usage. Pour les commentaires on peut utiliser Disqus, ç'est plutot bon pour un référencement externe et le partage social, et ça évite d'embarquer un module supplémentaire...

**Comment by juanito003** [comment]
Oui Disqus, c'est une option pour les commentaires. Sauf que cela soulève la question de centralisation des commentaires hébergés par un service tiers qui a le contrôle sur les commentaires, peut appliquer une censure, peut ne pas être disponible, etc.
Perso je ne suis pas à l'aise avec ça et si je décide d'installer mon site sur mon serveur avec pluXml, c'est justement pour avoir les commentaires hébergés sur mon serveur.
