### ISSUE TITLE
PluXml 5.8.16 - file(): read of 8192 bytes failed with errno=21

### ISSUE THREAD

**Issue by dadall** [pluxml/PluXml#841]
Salut,

Je viens de mettre à jour mon PluXmL et j'ai cette erreur qui apparaît en vert sur fond noir.

Ça ne m'empêche pas de naviguer, d'écrire ou de faire quoi que ce soit...

![Capture d’écran du 2024-12-01 18-20-53](https://github.com/user-attachments/assets/04d79cfa-7c4a-4099-8f14-ab587025e9c1)

Cordialement,

**Comment by bazooka07** [comment]
Salut,

Difficile de te répondre précisément avec ces infos.
En regardant le code de PluXml, je pense que tu as un sous-dossier dans les dossiers core/templates ou data/templates.
Peux-tu le confirmer ?
Je modifierai le code de PluXml pour éviter ce type d'erreur.

**Comment by bazooka07** [comment]
commit https://github.com/pluxml/PluXml/pull/844
On vérifie que le template est un fichieret que son mimetype est text/xml
