### ISSUE TITLE
administration : controles d'éditions des commentaires en dehors de l'écran

### ISSUE THREAD

**Issue by Deevad** [pluxml/PluXml#89]
![2015-02-17_screenshot_001](https://cloud.githubusercontent.com/assets/4021867/6224226/f50aaf86-b678-11e4-8631-eaa76a31aeb9.png)

C'est un bug qui survient après la migration des datas d'une version antérieur de Pluxml et quand certains commentaires sont fait de longues phrases: la taille de ces longues phrases se mets à étirer la géométrie horizontale du tableau ( copie d'écran ci-dessus : un zoom arrière avec Ctrl- de Firefox sur mes commentaires pour visualiser le bug ) . Ainsi étiré, les boutons d'édition des commentaires sont hors de porté de l'utilisateur final.

**Comment by Deevad** [comment]
Corrections provisoire:

Dans /core/admin/theme/theme.css , l.173
```
.scrollable-table .full-width td,
.scrollable-table .full-width th {
	padding-top: .2rem;
	padding-bottom: .2rem;
	white-space: nowrap;
}
```

supprimer le "white-space: nowrap;" pour n'avoir que:
```
.scrollable-table .full-width td,
.scrollable-table .full-width th {
	padding-top: .2rem;
	padding-bottom: .2rem;
}
```

**Comment by mistergraphx** [comment]
Hello, t'es sur que c'est pas pour corriger un bug de IE ? le white-space: nowrap; ??
généralement je l'utilise plutot pour ça, dans ce cas faudrait le conditionner pour IE plutot que de l'enlever ptet ...

mes 2 sesterces ;-)

**Comment by Deevad** [comment]
Aucune idée mistergraphx , c'est probable, je n'exclus pas. Je n'ai pas accès à Internet Explorer ici. ( tous mes ordis sont sous Linux ). En tout cas, cette option rends obsolète tout le management des commentaires ici sous Chromium/Chrome et Firefox, à moins d'avoir un écran qui fait 7000px de large. ( voir copie d'écran, il n'y a même pas de scrollbar ).
Il n'y a pas de conditionnel pour IE dans l'admin, même pas dans top.php, ou dans les en-tête des css. J'en déduis que la politique de code est d'essayer de trouver des solutions compatibles communes sans faire d’exception. 
Quelqu'un avec IE pourrait-il tester si c'est si grave sans le white-space: nowrap; ? Merci.

**Comment by Deevad** [comment]
Un peu de renseignement plus-tard ( http://www.w3schools.com/cssref/pr_text_white-space.asp ) : 
``` 
nowrap: 
----------
Sequences of whitespace will collapse into a single whitespace. Text will never wrap to the next line. The text continues on the same line until a <br> tag is encountered``` 

C'est donc lié à un autre bug de Pluxml : les commentaires sont enregistré dans la base de donnée sans besoin de </br> ou de <p></p> pour faire des retours à la ligne. C'est la conséquence de routine de sécurité qui détruise tout tag dans les commentaires, sauf quelques uns comme les liens de l'administrateur. Les commentaires avec 'nowrap' s'affichent donc en grande ligne continue; étirant le tableaux à perte de vue. 

Ce bug des commentaires sans </br> ou <p></p>  empêche d'ailleurs de d'enregistrer des paragraphes ou des retours à la ligne avec tout éditeur WYSIWYG dans Pluxml depuis plusieurs versions.

Faut t-il dans ce cas corriger le problème source de formatage du code des commentaires ? ou bien corriger l’exception qui les affichent ?

**Comment by Deevad** [comment]
Merci pour le fix très (très!) rapide. Je vais mettre à jour.
