### ISSUE TITLE
Theme admin sous linux

### ISSUE THREAD

**Issue by brouillon** [pluxml/PluXml#95]
Bonjour, 

Plusieurs remarques sur la nouvelle interface admin :

 - Sous linux l'affichage des tableaux dans l'admin impose un retour à la ligne à cause du filtre sur les catégories.Ce n'est pas très esthétique.
 - Les identifiants sont sur deux lignes, est ce l'effet voulu ?
 - Y aura t'il une façon simple de personnaliser le thème admin (intégralement ou juste en ajoutant un fichier css) ?

Voici une capture avec la version du 17/03@18h13
![Pluxml Admin](https://framapic.org/TMQPBzZt3vZF/qJbzxyh4)

Subsidiairement, dans la capture j'ai modifié la barre de menu à gauche avec firebug pour aligner le cadre gris avec le titre ('Liste des articles ...'). Juste parceque j'aime bien les choses alignés, pour ce faire j'ai brutalement supprimé les liens déconnexion et retour au site en me disant qu'il était possible de leur trouver une autre place.

**Comment by pluxml** [comment]
Bonjour 

Quel navigateur utilises-tu sous linux ?

> Y aura t'il une façon simple de personnaliser le thème admin (intégralement ou juste en ajoutant un fichier css) ?

oui c'est déjà implementé dans Paramètres > Configuration avancée, il y a le champ "Emplacement et nom du fichier css personnel pour la personnalisation de l'interface d'administration (option)"

**Comment by brouillon** [comment]
J'utilise Firefox, sous Chromium les entêtes sont correctes, juste les identifiants articles sur 2 lignes. pour les pages statiques ou les catégories l'identifiant n'est que sur une ligne ?!

Pour le css personnalisé de l'admin, c'est top merci.

**Comment by jos-pluxml** [comment]
Bonjour, 

Je vais tester l'admin sous Linux d'ici peu. Dés que j'aurais appliqué des modifications, je le signalerai ici.

**Comment by jos-pluxml** [comment]
Bonjour, 

L'affichage semble identique sous Linux et Windows (testé avec la dernière version d'Ubuntu et Firefox). Je pense qu'il n'y a pas de problèmes particuliers de ce coté là.
